### ISSUE TITLE
Migration Issues

### ISSUE THREAD

**Issue by jacobwoffenden** [snipe/snipe-it#1082]
I am currently migrating Snipe IT from Ubuntu + Apache to CentOS + NGINX

Database has been migrated from local MySQL to remote MariaDB - Connects successfully

Files have been transferred and NGINX is serving correctly with PHP (Can access Snipe Login)

When trying to login, I get the following (with debug turned on)
![screen shot 2015-08-19 at 16 56 07](https://cloud.githubusercontent.com/assets/9742606/9361489/96b6c022-4693-11e5-87f5-e7609b86bb2a.png)

And the following in ```app/storage/logs/log-fpm-fcgi-$date.txt```
```
[2015-08-19 15:59:38] production.ERROR: exception 'ErrorException' with message 'iconv_strlen(): Wrong charset, conversion from `8bit//IGNORE' to `UCS-4LE' is not allowed' in /var/www/ams/snipe-it/vendor/patchwork/utf8/class/Patchwork/PHP/Shim/Mbstring.php:299
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(8, 'iconv_strlen():...', '/var/www/ams/sn...', 299, Array)
#1 /var/www/ams/snipe-it/vendor/patchwork/utf8/class/Patchwork/PHP/Shim/Mbstring.php(299): iconv_strlen('$2y$10$vPNjtLKV...', '8bit//IGNORE')
#2 /var/www/ams/snipe-it/vendor/patchwork/utf8/class/Patchwork/Utf8/Bootup/mbstring.php(32): Patchwork\PHP\Shim\Mbstring::mb_strlen('$2y$10$vPNjtLKV...', '8bit')
#3 /var/www/ams/snipe-it/vendor/ircmaxell/password-compat/lib/password.php(269): mb_strlen('$2y$10$vPNjtLKV...', '8bit')
#4 /var/www/ams/snipe-it/vendor/ircmaxell/password-compat/lib/password.php(236): PasswordCompat\binary\_strlen('$2y$10$vPNjtLKV...')
#5 /var/www/ams/snipe-it/vendor/cartalyst/sentry/src/Cartalyst/Sentry/Hashing/NativeHasher.php(79): password_verify('Banana333@', '$2y$10$vPNjtLKV...')
#6 /var/www/ams/snipe-it/vendor/cartalyst/sentry/src/Cartalyst/Sentry/Users/Eloquent/Provider.php(148): Cartalyst\Sentry\Hashing\NativeHasher->checkhash('Banana333@', '$2y$10$vPNjtLKV...')
#7 /var/www/ams/snipe-it/vendor/cartalyst/sentry/src/Cartalyst/Sentry/Sentry.php(204): Cartalyst\Sentry\Users\Eloquent\Provider->findByCredentials(Array)
#8 /var/www/ams/snipe-it/bootstrap/compiled.php(3267): Cartalyst\Sentry\Sentry->authenticate(Array, 0)
#9 /var/www/ams/snipe-it/app/controllers/AuthController.php(45): Illuminate\Support\Facades\Facade::__callStatic('authenticate', Array)
#10 /var/www/ams/snipe-it/app/controllers/AuthController.php(45): Cartalyst\Sentry\Facades\Laravel\Sentry::authenticate(Array, 0)
#11 [internal function]: AuthController->postSignin()
#12 /var/www/ams/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#13 /var/www/ams/snipe-it/bootstrap/compiled.php(5820): Illuminate\Routing\Controller->callAction('postSignin', Array)
#14 /var/www/ams/snipe-it/bootstrap/compiled.php(5808): Illuminate\Routing\ControllerDispatcher->call(Object(AuthController), Object(Illuminate\Routing\Route), 'postSignin')
#15 /var/www/ams/snipe-it/bootstrap/compiled.php(5007): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AuthController', 'postSignin')
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /var/www/ams/snipe-it/bootstrap/compiled.php(5366): call_user_func_array(Object(Closure), Array)
#18 /var/www/ams/snipe-it/bootstrap/compiled.php(5032): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 /var/www/ams/snipe-it/bootstrap/compiled.php(5020): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#20 /var/www/ams/snipe-it/bootstrap/compiled.php(721): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /var/www/ams/snipe-it/bootstrap/compiled.php(702): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /var/www/ams/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/ams/snipe-it/bootstrap/compiled.php(7783): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/ams/snipe-it/bootstrap/compiled.php(8390): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/ams/snipe-it/bootstrap/compiled.php(8337): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/ams/snipe-it/bootstrap/compiled.php(10998): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/ams/snipe-it/bootstrap/compiled.php(664): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#28 /var/www/ams/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#29 {main} [] []
```

**Comment by snipe** [comment]
Going to need a little more info than that. Please see the docs on getting help. http://docs.snipeitapp.com/getting-help.html

**Comment by jacobwoffenden** [comment]
@snipe Updated - Accidentally pressed enter :(

**Comment by jacobwoffenden** [comment]
reinstalling ```php-mbstring``` fixed this for me

Source: https://github.com/barryvdh/laravel-dompdf/issues/35
