### ISSUE TITLE
(2.0RC) DataTables Warning

### ISSUE THREAD

**Issue by Gehirnfussel** [snipe/snipe-it#1104]
Similar to #839 I get an Javascript error when I'm opening Assets > Deleted:

`DataTables warning: table id=Al9ZtfGR - Ajax error. For more information about this error, please see       http://datatables.net/tn/7`

(ID varies on every visit).

Updated from 1.1 to 2.0 RC today

**Comment by snipe** [comment]
Did you run migrations?

**Comment by snipe** [comment]
Also, we need to see what's in your error logs. Datatables errors aren't particularly useful.

**Comment by Gehirnfussel** [comment]
Hi again,
sorry, of couse I should have included more details. 

Server is running Ubuntu, PHP 5.5.9-1ubuntu4.11, mysqld 5.5.44-0ubuntu0.14.04.1
Browser: Google Chrome Version 45.0.2454.46 beta-m (64-bit)
OS: Windows 7-SP1 (don't think it matters, but anyway :D)

Logfile  app/storage/logs/log-apache2handler-2015-08-21.txt
```
[2015-08-21 15:45:22] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/html/snipe-it2/app/controllers/admin/AssetsController.php:1024
Stack trace:
#0 /var/www/html/snipe-it2/app/controllers/admin/AssetsController.php(1024): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/html/s...', 1024, Array)
#1 [internal function]: Controllers\Admin\AssetsController->Controllers\Admin\{closure}(Object(Asset))
#2 /var/www/html/snipe-it2/vendor/chumper/datatable/src/Chumper/Datatable/Columns/FunctionColumn.php(15): call_user_func(Object(Closure), Object(Asset))
#3 /var/www/html/snipe-it2/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php(264): Chumper\Datatable\Columns\FunctionColumn->run(Object(Asset))
#4 [internal function]: Chumper\Datatable\Engines\CollectionEngine->Chumper\Datatable\Engines\{closure}(Object(Asset), 0)
#5 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Support/Collection.php(344): array_map(Object(Closure), Array, Array)
#6 /var/www/html/snipe-it2/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php(270): Illuminate\Support\Collection->map(Object(Closure))
#7 /var/www/html/snipe-it2/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php(123): Chumper\Datatable\Engines\CollectionEngine->compileArray(Object(Illuminate\Support\Collection))
#8 /var/www/html/snipe-it2/vendor/chumper/datatable/src/Chumper/Datatable/Engines/BaseEngine.php(225): Chumper\Datatable\Engines\CollectionEngine->internalMake(Object(Illuminate\Support\Collection), Array)
#9 /var/www/html/snipe-it2/app/controllers/admin/AssetsController.php(1133): Chumper\Datatable\Engines\BaseEngine->make()
#10 [internal function]: Controllers\Admin\AssetsController->getDatatable('Deleted')
#11 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#12 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getDatatable', Array)
#13 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AssetsController), Object(Illuminate\Routing\Route), 'getDatatable')
#14 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'getDatatable')
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('Deleted')
#16 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#17 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#19 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#21 /var/www/html/snipe-it2/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#22 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/snipe-it2/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#27 /var/www/html/snipe-it2/public/index.php(49): Illuminate\Foundation\Application->run()
#28 {main} [] []
```

again, I am unsure what you mean my migrations.
(If you mean php composer.phar install; php composer.phar dump-autoload; php artisan migrate — yes, did that)

**Comment by snipe** [comment]
MIgrations = `php artisan migrate`: http://docs.snipeitapp.com/upgrading.html

**Comment by snipe** [comment]
(Also in the release notes) https://github.com/snipe/snipe-it/releases/tag/v2.0-RC-1

**Comment by Gehirnfussel** [comment]
Yes, did it.
But just to be sure just did it again.
´´´
**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? y
Nothing to migrate.
´´´

**Comment by snipe** [comment]
Can you show me what's on line 1024 of ` /var/www/html/snipe-it2/app/controllers/admin/AssetsController.php`?

**Comment by Gehirnfussel** [comment]
`                } elseif ($assets->model->deleted_at=='') {`

**Comment by snipe** [comment]
Have you manually manipulated your data in any way? `$assets->model` should definitely be an object unless the model has been manually deleted from the database.

**Comment by Gehirnfussel** [comment]
At least I don't remember doing anything like this. (I think I never even been in the database of my installation).

**Comment by snipe** [comment]
Can you pull down the latest off of develop and see if anything changes?

**Comment by Gehirnfussel** [comment]
Just did a complete 'reinstall' (pulled latest production).
Copied the app/config/production/app.php and app/config/production/database.php files and did all composer and artisan stuff again (no errors here).
Same error.

**Comment by snipe** [comment]
Can you show me the error again? Curious to see if the line number changed.

Do you know anything about SQL? Can you look up the assets in the database and tell me if any of them are missing a `model_id`? How did your data get in there in the first place? Did you import it via the built-in tools, or did you manually enter?

**Comment by Gehirnfussel** [comment]
So, here's the error log again:

```
[2015-08-21 22:30:27] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/html/snipe-it2/app/controllers/admin/AssetsController.php:1024
Stack trace:
#0 /var/www/html/snipe-it2/app/controllers/admin/AssetsController.php(1024): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/html/s...', 1024, Array)
#1 [internal function]: Controllers\Admin\AssetsController->Controllers\Admin\{closure}(Object(Asset))
#2 /var/www/html/snipe-it2/vendor/chumper/datatable/src/Chumper/Datatable/Columns/FunctionColumn.php(15): call_user_func(Object(Closure), Object(Asset))
#3 /var/www/html/snipe-it2/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php(264): Chumper\Datatable\Columns\FunctionColumn->run(Object(Asset))
#4 [internal function]: Chumper\Datatable\Engines\CollectionEngine->Chumper\Datatable\Engines\{closure}(Object(Asset), 0)
#5 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Support/Collection.php(344): array_map(Object(Closure), Array, Array)
#6 /var/www/html/snipe-it2/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php(270): Illuminate\Support\Collection->map(Object(Closure))
#7 /var/www/html/snipe-it2/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php(123): Chumper\Datatable\Engines\CollectionEngine->compileArray(Object(Illuminate\Support\Collection))
#8 /var/www/html/snipe-it2/vendor/chumper/datatable/src/Chumper/Datatable/Engines/BaseEngine.php(225): Chumper\Datatable\Engines\CollectionEngine->internalMake(Object(Illuminate\Support\Collection), Array)
#9 /var/www/html/snipe-it2/app/controllers/admin/AssetsController.php(1133): Chumper\Datatable\Engines\BaseEngine->make()
#10 [internal function]: Controllers\Admin\AssetsController->getDatatable('Deleted')
#11 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#12 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getDatatable', Array)
#13 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AssetsController), Object(Illuminate\Routing\Route), 'getDatatable')
#14 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'getDatatable')
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('Deleted')
#16 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#17 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#19 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#21 /var/www/html/snipe-it2/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#22 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/snipe-it2/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/snipe-it2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#27 /var/www/html/snipe-it2/public/index.php(49): Illuminate\Foundation\Application->run()
#28 {main} [] []
```

I know *some* stuff about SQL and took a look into the assets tables, checked all 170 entries but could not find any entry without a model_id.

**Comment by snipe** [comment]
I still can't imagine why you'd be seeing this, and I can't reproduce it on my end, but can you try changing line 1024 in the `app/controllers/AssetsController.php` from:

```
} elseif ($assets->model->deleted_at=='') {
```

to:

```
} elseif ($assets->deleted_at!='') {
```

And tell me if that helps? This is hard to put out a fix for since I can't reproduce it anywhere :(

**Comment by snipe** [comment]
If that doesn't work, try changing line 1024 to:

```
} else {
```

**Comment by Gehirnfussel** [comment]
So `} elseif ($assets->deleted_at!='') {`seems to fix the problem. (not JS error nor an entry in the logfile)
