### ISSUE TITLE
Password reset mails generating internal 500 errors. Emails for new user create are working fine.

### ISSUE THREAD

**Issue by deegecrotty** [snipe/snipe-it#1130]
output of log file.
[2015-08-28 16:35:32] production.ERROR: exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [dominic.crotty1] does not comply with RFC 2822, 3.6.2.' in C:\xampp\htdocs\snipeit\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\Headers\MailboxHeader.php:348

**Comment by snipe** [comment]
That's not an email address tho. Does that user actually have an email address associated with the or just a username?

**Comment by deegecrotty** [comment]
```
Stack trace:
#0 C:\xampp\htdocs\snipeit\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\Headers\MailboxHeader.php(263): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('dominic.crotty1')
#1 C:\xampp\htdocs\snipeit\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\Headers\MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 C:\xampp\htdocs\snipeit\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\Headers\MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 C:\xampp\htdocs\snipeit\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\SimpleHeaderFactory.php(58): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 C:\xampp\htdocs\snipeit\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\SimpleHeaderSet.php(68): Swift_Mime_SimpleHeaderFactory->createMailboxHeader('To', Array)
#5 C:\xampp\htdocs\snipeit\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\SimpleMessage.php(323): Swift_Mime_SimpleHeaderSet->addMailboxHeader('To', Array)
#6 C:\xampp\htdocs\snipeit\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\SimpleMessage.php(299): Swift_Mime_SimpleMessage->setTo(Array)
#7 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Mail\Message.php(131): Swift_Mime_SimpleMessage->addTo('dominic.crotty1', 'Dominic Crotty')
#8 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Mail\Message.php(76): Illuminate\Mail\Message->addAddresses('dominic.crotty1', 'Dominic Crotty', 'To')
#9 C:\xampp\htdocs\snipeit\app\controllers\AuthController.php(226): Illuminate\Mail\Message->to('dominic.crotty1', 'Dominic Crotty')
#10 [internal function]: AuthController->{closure}(Object(Illuminate\Mail\Message))
#11 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(363): call_user_func(Object(Closure), Object(Illuminate\Mail\Message))
#12 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(142): Illuminate\Mail\Mailer->callMessageBuilder(Object(Closure), Object(Illuminate\Mail\Message))
#13 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(214): Illuminate\Mail\Mailer->send('emails.forgot-p...', Array, Object(Closure))
#14 C:\xampp\htdocs\snipeit\app\controllers\AuthController.php(228): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#15 C:\xampp\htdocs\snipeit\app\controllers\AuthController.php(228): Illuminate\Support\Facades\Mail::send('emails.forgot-p...', Array, Object(Closure))
#16 [internal function]: AuthController->postForgotPassword()
#17 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#18 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postForgotPassw...', Array)
#19 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(AuthController), Object(Illuminate\Routing\Route), 'postForgotPassw...')
#20 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AuthController', 'postForgotPassw...')
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#22 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#23 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\snipeit\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#28 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#29 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#30 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#31 C:\xampp\htdocs\snipeit\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#32 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#33 C:\xampp\htdocs\snipeit\public\index.php(49): Illuminate\Foundation\Application->run()
```

**Comment by deegecrotty** [comment]
It asks for Username on the forgot password page, should i just using email adddress instead ?

**Comment by snipe** [comment]
Try with an email address instead.

**Comment by snipe** [comment]
If you pull down the latest from develop, this is fixed in there I think
