### ISSUE TITLE
Server Error 500 when upload logo

### ISSUE THREAD

**Issue by imie** [snipe/snipe-it#1188]
i got these error when i tried to upload a logo.

i tried to upload jpg and png format. even different picture, all receive server error. did i missing something ? php-gd2.dll is enabled.

[2015-09-22 14:55:21] production.ERROR: exception 'Intervention\Image\Exception\NotReadableException' with message 'Image source not readable' in C:\inetpub\wwwroot\snipe-it\vendor\intervention\image\src\Intervention\Image\AbstractDecoder.php:302
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\intervention\image\src\Intervention\Image\AbstractDriver.php(64): Intervention\Image\AbstractDecoder->init(false)
#1 C:\inetpub\wwwroot\snipe-it\vendor\intervention\image\src\Intervention\Image\ImageManager.php(50): Intervention\Image\AbstractDriver->init(false)
#2 C:\inetpub\wwwroot\snipe-it\vendor\intervention\image\src\Intervention\Image\ImageManagerStatic.php(57): Intervention\Image\ImageManager->make(false)
#3 C:\inetpub\wwwroot\snipe-it\app\controllers\admin\SettingsController.php(104): Intervention\Image\ImageManagerStatic::make(false)
#4 [internal function]: Controllers\Admin\SettingsController->postEdit()
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#6 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5847): Illuminate\Routing\Controller->callAction('postEdit', Array)
#7 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\SettingsController), Object(Illuminate\Routing\Route), 'postEdit')
#8 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'postEdit')
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5398): call_user_func_array(Object(Closure), Array)
#11 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 C:\inetpub\wwwroot\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#16 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(7825): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#17 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(11088): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 C:\inetpub\wwwroot\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []

**Comment by imie** [comment]
just found the solution.

need to give users permission to windows/temp and also iis user.

ttorres91 commented on 7 Feb

I was able to get it to work in IIS by granting read only access to the Windows Users group (Computer Name\Users). Apparently granting IIS access alone is not enough for the Windows security model lol.

Thanks again guys for all the help, my department is really excited about this app so we can get rid of all the spreadsheets we have.
