### ISSUE TITLE
After upgrading to 2.0.5 there is no users in admin/users page 

### ISSUE THREAD

**Issue by vabue** [snipe/snipe-it#1369]
Hello.

Just upgraded my working 2.0.4 to 2.0.5. Everything works fine accept that People listing is empty - http://take.ms/CovW2

But users itself exist, I can access their profiles through assets or locations pages - http://take.ms/Nx40p.

In the storage logs such errors:
```
root@web:/home/www/snipe/app/storage/logs# tail -f -n 0 ./log-fpm-fcgi-2015-11-21.txt
[2015-11-21 09:48:31] production.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'location' in 'order clause'' in /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php:299
Stack trace:
#0 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(299): PDO->prepare('select count(*)...')
#1 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select count(*)...', Array)
#2 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#3 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#4 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1412): Illuminate\Database\Connection->select('select count(*)...', Array)
#5 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1397): Illuminate\Database\Query\Builder->runSelect()
#6 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1384): Illuminate\Database\Query\Builder->getFresh(Array)
#7 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1830): Illuminate\Database\Query\Builder->get(Array)
#8 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1768): Illuminate\Database\Query\Builder->aggregate('count', Array)
#9 [internal function]: Illuminate\Database\Query\Builder->count()
#10 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#11 /home/www/snipe/app/controllers/admin/UsersController.php(879): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#12 /home/www/snipe/app/controllers/admin/UsersController.php(879): Illuminate\Database\Eloquent\Builder->count()
#13 [internal function]: Controllers\Admin\UsersController->getDatatable()
#14 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#15 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getDatatable', Array)
#16 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\UsersController), Object(Illuminate\Routing\Route), 'getDatatable')
#17 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'getDatatable')
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#19 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#20 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#22 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 /home/www/snipe/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#25 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#26 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#27 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#28 /home/www/snipe/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#29 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#30 /home/www/snipe/public/index.php(49): Illuminate\Foundation\Application->run()
#31 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'location' in 'order clause' (SQL: select count(*) as aggregate from `users` where `users`.`deleted_at` is null order by `location` desc)' in /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1412): Illuminate\Database\Connection->select('select count(*)...', Array)
#3 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1397): Illuminate\Database\Query\Builder->runSelect()
#4 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1384): Illuminate\Database\Query\Builder->getFresh(Array)
#5 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1830): Illuminate\Database\Query\Builder->get(Array)
#6 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1768): Illuminate\Database\Query\Builder->aggregate('count', Array)
#7 [internal function]: Illuminate\Database\Query\Builder->count()
#8 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#9 /home/www/snipe/app/controllers/admin/UsersController.php(879): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#10 /home/www/snipe/app/controllers/admin/UsersController.php(879): Illuminate\Database\Eloquent\Builder->count()
#11 [internal function]: Controllers\Admin\UsersController->getDatatable()
#12 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#13 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getDatatable', Array)
#14 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\UsersController), Object(Illuminate\Routing\Route), 'getDatatable')
#15 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'getDatatable')
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#18 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#20 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 /home/www/snipe/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#23 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#24 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#25 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#26 /home/www/snipe/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#27 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#28 /home/www/snipe/public/index.php(49): Illuminate\Foundation\Application->run()
#29 {main} [] []
```

**Comment by snipe** [comment]
Can you clear your cookies and try again?
