### ISSUE TITLE
Cyrillic symbols in Asset Model Name lead to 500 error

### ISSUE THREAD

**Issue by vabue** [snipe/snipe-it#1371]
~~While uploading asset image with name G3(2).jpg I've got 500 error.~~
Snipe-it version 2.0.5.

**Comment by snipe** [comment]
I need an actual error message, please.

**Comment by vabue** [comment]
Sorry, it's my mistake. Everything is OK with filename. 

Error comes when I'm using cyrillic symbols in Asset Model Name. For example 'Принтер'. http://www.youtube.com/watch?v=YC-_20S5nF8

```
2015-11-21 19:25:55] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation '='' in /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php:301
Stack trace:
#0 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): PDOStatement->execute(Array)
#1 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select count(*)...', Array)
#2 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#3 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#4 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1412): Illuminate\Database\Connection->select('select count(*)...', Array)
#5 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1397): Illuminate\Database\Query\Builder->runSelect()
#6 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1384): Illuminate\Database\Query\Builder->getFresh(Array)
#7 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1830): Illuminate\Database\Query\Builder->get(Array)
#8 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1768): Illuminate\Database\Query\Builder->aggregate('count', Array)
#9 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Validation/DatabasePresenceVerifier.php(57): Illuminate\Database\Query\Builder->count()
#10 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(1020): Illuminate\Validation\DatabasePresenceVerifier->getCount('models', 'deleted_at', '?????????????? ...', NULL, 'id', Array)
#11 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(322): Illuminate\Validation\Validator->validateUnique('name', '?????????????? ...', Array, Object(Illuminate\Validation\Validator))
#12 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(283): Illuminate\Validation\Validator->validate('name', 'unique:models,d...')
#13 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(297): Illuminate\Validation\Validator->passes()
#14 /home/www/snipe/app/controllers/admin/ModelsController.php(215): Illuminate\Validation\Validator->fails()
#15 [internal function]: Controllers\Admin\ModelsController->postEdit('184')
#16 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#17 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postEdit', Array)
#18 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\ModelsController), Object(Illuminate\Routing\Route), 'postEdit')
#19 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postEdit')
#20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('184')
#21 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#22 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#23 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#24 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#26 /home/www/snipe/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#27 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#28 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#29 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#30 /home/www/snipe/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#31 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#32 /home/www/snipe/public/index.php(49): Illuminate\Foundation\Application->run()
#33 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation '=' (SQL: select count(*) as aggregate from `models` where `deleted_at` = Принтер Zebra 2844)' in /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1412): Illuminate\Database\Connection->select('select count(*)...', Array)
#3 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1397): Illuminate\Database\Query\Builder->runSelect()
#4 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1384): Illuminate\Database\Query\Builder->getFresh(Array)
#5 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1830): Illuminate\Database\Query\Builder->get(Array)
#6 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1768): Illuminate\Database\Query\Builder->aggregate('count', Array)
#7 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Validation/DatabasePresenceVerifier.php(57): Illuminate\Database\Query\Builder->count()
#8 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(1020): Illuminate\Validation\DatabasePresenceVerifier->getCount('models', 'deleted_at', '?????????????? ...', NULL, 'id', Array)
#9 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(322): Illuminate\Validation\Validator->validateUnique('name', '?????????????? ...', Array, Object(Illuminate\Validation\Validator))
#10 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(283): Illuminate\Validation\Validator->validate('name', 'unique:models,d...')
#11 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(297): Illuminate\Validation\Validator->passes()
#12 /home/www/snipe/app/controllers/admin/ModelsController.php(215): Illuminate\Validation\Validator->fails()
#13 [internal function]: Controllers\Admin\ModelsController->postEdit('184')
#14 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#15 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postEdit', Array)
#16 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\ModelsController), Object(Illuminate\Routing\Route), 'postEdit')
#17 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postEdit')
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('184')
#19 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#20 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#22 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 /home/www/snipe/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#25 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#26 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#27 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#28 /home/www/snipe/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#29 /home/www/snipe/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#30 /home/www/snipe/public/index.php(49): Illuminate\Foundation\Application->run()
#31 {main} [] []
```

**Comment by snipe** [comment]
` where `deleted_at` = Принтер Zebra 2844`

That's.... very confusing...

**Comment by snipe** [comment]
Okay, I've got a little more info on this, although not actually a fix. :-/ 

It's either an issue related to this:
http://stackoverflow.com/questions/10379299/operator-like-field-type-timestamp-and-cyrillic-mysql-bug

Or the validation that we're using in `app/models/Model.php`:

```
        'name'   		=> 'required|alpha_space|min:2|max:255|unique:models,deleted_at,NULL',
```

The fact that your query looks like it's trying to match the `deleted_at` field to text makes me think it might be the validation, but I'm not sure. This only seems to happen with non-latin characters, but I can reproduce it on my end. 

(That type of field validation, where you're telling it that `name` should be unique in the models table but only if `deleted_at` is NULL isn't particularly well documented.)

If anyone else has any input or info here, it would be appreciated. 

To reproduce this, simply try to create a model with the name `台电 V919`.

**Comment by snipe** [comment]
I just pushed out a change to develop that I hope/think should fix this issue

**Comment by vabue** [comment]
:+1: 
Thank you! Today I'll try to reproduce it.
