### ISSUE TITLE
Bulk edit tool returns garbage data

### ISSUE THREAD

**Issue by unbkbl** [snipe/snipe-it#1485]
Hi!

I was trying to use the bulk edit tool but it returns a page with "garbage" data like this

qa�㢏�y�Db�*@�s���

Any Idea what could it be? I'm using IIS 7, WS 2008r2 and...
Snipe-IT version 	v2.0.5-pre-191-g948be5c
PHP Version 	5.4.45
Laravel Version 	4.2.17 

The only entries in the logs are:

[2015-12-15 09:26:57] production.ERROR: ldap_get_attributes() expects parameter 2 to be resource, boolean given [] []
[2015-12-15 09:27:17] production.DEBUG: Authenticating user against LDAP. [] []
[2015-12-15 09:27:17] production.DEBUG: valid login [] []
[2015-12-15 22:03:44] production.DEBUG: Authenticating user against LDAP. [] []
[2015-12-15 22:03:48] production.DEBUG: valid login [] []
[2015-12-15 22:13:14] production.DEBUG: Authenticating user against LDAP. [] []
[2015-12-15 22:13:14] production.DEBUG: valid login [] []
[2015-12-15 22:19:29] production.DEBUG: Authenticating user against LDAP. [] []
[2015-12-15 22:19:29] production.DEBUG: valid login [] []
[2015-12-15 22:24:13] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php:5751
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 C:\inetpub\wwwroot\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(7825): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#7 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(11104): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 C:\inetpub\wwwroot\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []

Thanks for any help in advance,

Dan

**Comment by unbkbl** [comment]
any ideas?
![confused john](https://cloud.githubusercontent.com/assets/7104480/11895658/882cefec-a578-11e5-9734-ee5d0670e890.gif)

**Comment by snipe** [comment]
Every time you try to bulk edit, does it add a new `production.ERROR: ldap_get_attributes() expects parameter 2 to be resource, boolean given [] []` error?
