### ISSUE TITLE
500 error on login Invalid Data

### ISSUE THREAD

**Issue by kitcallen** [snipe/snipe-it#1514]
Getting a 500 error after attempting to login. It does it with correct or incorrect username/password

Most current Snipe-IT
Apache2 on Ubuntu 14.04

Illuminate \ Encryption \ DecryptException: Invalid data.

```[2015-12-22 17:40:17] production.ERROR: exception 'Illuminate\Encryption\DecryptException' with message 'Invalid data.' in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:139
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(89): Illuminate\Encryption\Encrypter->getJsonPayload(NULL)
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\Encryption\Encrypter->decrypt(NULL)
#2 /var/www/snipeit/app/controllers/AuthController.php(36): Illuminate\Support\Facades\Facade::__callStatic('decrypt', Array)
#3 /var/www/snipeit/app/controllers/AuthController.php(36): Illuminate\Support\Facades\Crypt::decrypt(NULL)
#4 /var/www/snipeit/app/controllers/AuthController.php(161): AuthController->ldap('ict@shapeways.c...', 'Pajama-Oven', true)
#5 [internal function]: AuthController->postSignin()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postSignin', Array)
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(AuthController), Object(Illuminate\Routing\Route), 'postSignin')
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AuthController', 'postSignin')
#10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#16 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#22 /var/www/snipeit/public/index.php(49): Illuminate\Foundation\Application->run()
#23 {main} [] []```

**Comment by snipe** [comment]
Most recent version or what branch? Or most recent release you mean? I think this is already a known issue and is discussed elsewhere, but it should only be throwing that's if the user name is bad. Please double check your credentials.

**Comment by kitcallen** [comment]
I cloned from master today. It looks like the problem is trying to use a bad database backup.
