### ISSUE TITLE
Problem adding a license after update

### ISSUE THREAD

**Issue by dc53000** [snipe/snipe-it#1567]
This is on version v2.0.5-pre-191-g948be5c.

It occurs after filling in license information for a new license and then hitting "Save". There appears to be no company drop-down with which to pick the company. I suspect the gui not being mapped to the database structure is the root problem, but I am no laravel expert.

There is also no company drop-down menu when editing existing licenses.

```[2016-01-04 12:08:08] production.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`snipedb`.`licenses`, CONSTRAINT `licenses_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`))' in /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:369
Stack trace:
#0 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php(369): PDOStatement->execute(Array)
#1 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `li...', Array)
#2 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `li...', Array, Object(Closure))
#3 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `li...', Array, Object(Closure))
#4 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `li...', Array)
#5 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `li...', Array)
#6 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `li...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#9 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1550): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1456): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /home/www/sipe/snipe-it/app/controllers/admin/LicensesController.php(148): Illuminate\Database\Eloquent\Model->save()
#14 [internal function]: Controllers\Admin\LicensesController->postCreate()
#15 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#16 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#17 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\LicensesController), Object(Illuminate\Routing\Route), 'postCreate')
#18 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postCreate')
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#20 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#21 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#25 /home/www/sipe/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#26 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#27 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#28 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#29 /home/www/sipe/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#30 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#31 /home/www/sipe/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#32 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`snipedb`.`licenses`, CONSTRAINT `licenses_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)) (SQL: insert into `licenses` (`purchase_cost`, `supplier_id`, `maintained`, `reassignable`, `purchase_order`, `name`, `serial`, `license_email`, `license_name`, `notes`, `order_number`, `seats`, `purchase_date`, `depreciation_id`, `company_id`, `expiration_date`, `user_id`, `updated_at`, `created_at`) values (, 7, 0, 1, , test, 12345, , , , , 6, , 0, , , 91, 2016-01-04 12:08:08, 2016-01-04 12:08:08))' in /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `li...', Array, Object(Closure))
#1 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `li...', Array, Object(Closure))
#2 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `li...', Array)
#3 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `li...', Array)
#4 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `li...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#7 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1550): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1456): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /home/www/sipe/snipe-it/app/controllers/admin/LicensesController.php(148): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: Controllers\Admin\LicensesController->postCreate()
#13 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#15 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\LicensesController), Object(Illuminate\Routing\Route), 'postCreate')
#16 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postCreate')
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#19 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /home/www/sipe/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#25 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#26 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#27 /home/www/sipe/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#28 /home/www/sipe/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#29 /home/www/sipe/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#30 {main} [] []

```

**Comment by dc53000** [comment]
Hm, this doesn't happen on the demo site, and the demo site has the company dropdown in the gui. So, I will update to the latest pre-release and see if it is fixed there.

**Comment by dc53000** [comment]
Yup, seems to be fixed in v2.0.6-169-g4aa3768, so nevermind. Thanks!
