### ISSUE TITLE
Invalid data. Exception.

### ISSUE THREAD

**Issue by PermaNulled** [snipe/snipe-it#1628]
I had to manually perform the steps from the snipe.sh and I got most of it installed, the DB created and etc but every time I try to log-in I'm presented with this Invalid Data exception.

Ubuntu 14.04.3 LTS
PHP 5.5.9-1ubuntu4.14 (fpm-fcgi) (built: Oct 28 2015 01:38:24)
nginx version: nginx/1.4.6 (Ubuntu)

I'm trying to use the DB login not the ldap login, just not sure how to disable LDAP logins... and don't see where the install script handles setting what method is used for authentication.

Stack trace:
    [21:46:45] LOG.error: exception 'Illuminate\Encryption\DecryptException' with message 'Invalid data.' in /home/snipe-it/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:139
    Stack trace:
    #0 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(89): Illuminate\Encryption\Encrypter->getJsonPayload(NULL)
    #1 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\Encryption\Encrypter->decrypt(NULL)
    #2 /home/snipe-it/app/controllers/AuthController.php(36): Illuminate\Support\Facades\Facade::__callStatic('decrypt', Array)
    #3 /home/snipe-it/app/controllers/AuthController.php(36): Illuminate\Support\Facades\Crypt::decrypt(NULL)
    #4 /home/snipe-it/app/controllers/AuthController.php(161): AuthController->ldap('test', 'test', true)
    #5 [internal function]: AuthController->postSignin()
    #6 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
    #7 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postSignin', Array)
    #8 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(AuthController), Object(Illuminate\Routing\Route), 'postSignin')
    #9 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AuthController', 'postSignin')
    #10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
    #11 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
    #12 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
    #13 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
    #14 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
    #15 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
    #16 /home/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
    #17 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
    #18 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
    #19 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
    #20 /home/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
    #21 /home/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
    #22 /home/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
    #23 {main}

    errorlog

**Comment by PermaNulled** [comment]
I believe I was typing the wrong username I commented the LDAP lines inside of the AuthController.php and then attempted login and got wrong user/pass message, used the correct user and it's functioning now.
