### ISSUE TITLE
creating new asset from asset models page causes 500 error

### ISSUE THREAD

**Issue by leobg** [snipe/snipe-it#1743]
Whenever I try to create new asset by clicking create new asset in the asset models list I get the following error:
```

[2016-02-09 22:16:59] production.ERROR: exception 'ErrorException' with message 'Undefined index: fields' in /var/www/snipe-it-2.1.0/app/controllers/admin/AssetsController.php:113
Stack trace:
#0 /var/www/snipe-it-2.1.0/app/controllers/admin/AssetsController.php(113): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/var/www/snipe-...', 113, Array)
#1 [internal function]: Controllers\Admin\AssetsController->postCreate()
#2 /var/www/snipe-it-2.1.0/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /var/www/snipe-it-2.1.0/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#4 /var/www/snipe-it-2.1.0/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AssetsController), Object(Illuminate\Routing\Route), 'postCreate')
#5 /var/www/snipe-it-2.1.0/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'postCreate')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/snipe-it-2.1.0/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#8 /var/www/snipe-it-2.1.0/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/snipe-it-2.1.0/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/snipe-it-2.1.0/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/snipe-it-2.1.0/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/snipe-it-2.1.0/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/snipe-it-2.1.0/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/snipe-it-2.1.0/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/snipe-it-2.1.0/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/snipe-it-2.1.0/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/snipe-it-2.1.0/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /var/www/snipe-it-2.1.0/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []
```

I tried the usual stuff, deleted cache, views, database migration says "nothing to migrate" 
Any insight what might be causing this? 
Running the latest stable release (2.1.0)

**Comment by snipe** [comment]
Please check the url in your `app/config/production/app.php`. If that is wrong, the ajax will not load correctly

**Comment by leobg** [comment]
Thanks for the super quick response. URL is definitely correct. If I create asset by cloning existing one or just go from main add asset link it works fine. Error only occurs if I initiate new asset by clicking create asset from asset model context.

**Comment by snipe** [comment]
Can you tell me if you're getting any browser console errors?

**Comment by snipe** [comment]
Actually, never mind - I believe this was already fixed on the master branch
