### ISSUE TITLE
Fatal Error when adding new accessory without location

### ISSUE THREAD

**Issue by icanhazpython** [snipe/snipe-it#1815]
#### Expected Behavior
Accessory is added

#### Actual Behavior
If location is omitted/not selected, new accessory will not save, yielding a 500 error.

#### Stack Trace
```
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'location_id' at row 1 (SQL: insert into `accessories` (`name`, `category_id`, `location_id`, `company_id`, `order_number`, `purchase_date`, `purchase_cost`, `qty`, `user_id`, `updated_at`, `created_at`) values (IP Phone Power Supply, 25, , , , , , 1, 1, 2016-03-02 15:42:09, 2016-03-02 15:42:09))' in /vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ac...', Array, Object(Closure))
#1 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ac...', Array, Object(Closure))
#2 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ac...', Array)
#3 /vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ac...', Array)
#4 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ac...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#7 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1550): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1456): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /app/controllers/admin/AccessoriesController.php(98): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: Controllers\Admin\AccessoriesController->postCreate()
#13 /vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#15 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AccessoriesController), Object(Illuminate\Routing\Route), 'postCreate')
#16 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Add...', 'postCreate')
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#19 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#25 /vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#26 /vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#27 /vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#28 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#29 /public/index.php(49): Illuminate\Foundation\Application->run()
#30 {main} [] []
```

**Comment by ddreier** [comment]
You're missing at least half of the information requested on the [Getting Help](http://snipe.github.io/snipe-it/getting-help.html) page.
