### ISSUE TITLE
500 Error on New Install

### ISSUE THREAD

**Issue by misilot** [snipe/snipe-it#1840]
#### Expected Behavior (or desired behavior if a feature request)

Login page?
-----

#### Actual Behavior

500 Error

Here is the output from the log in app/storage/logs/*apache*.log
```
Stack trace:
#0 /var/www/vhosts/development/staging7/snipe-it/app/storage/views/f3a02d09a768a44080912c422d274821(12): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/vhosts...', 12, Array)
#1 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(37): include('/var/www/vhosts...')
#2 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/vhosts...', Array)
#3 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/var/www/vhosts...', Array)
#4 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#5 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#6 /var/www/vhosts/development/staging7/snipe-it/app/storage/views/0b288383871cb16d2dcccc0a6b0355b7(67): Illuminate\View\View->render()
#7 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(37): include('/var/www/vhosts...')
#8 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/vhosts...', Array)
#9 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/var/www/vhosts...', Array)
#10 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#11 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#12 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#13 /var/www/vhosts/development/staging7/snipe-it/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#14 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#15 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#16 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#17 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#18 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#19 /var/www/vhosts/development/staging7/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#22 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/vhosts/development/staging7/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#25 /var/www/vhosts/development/staging7/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#26 {main}

Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /var/www/vhosts/development/staging7/snipe-it/app/views/backend/layouts/default.blade.php)' in /var/www/vhosts/development/staging7/snipe-it/app/storage/views/f3a02d09a768a44080912c422d274821:12
Stack trace:
#0 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/vhosts...', Array)
#2 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/var/www/vhosts...', Array)
#3 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /var/www/vhosts/development/staging7/snipe-it/app/storage/views/0b288383871cb16d2dcccc0a6b0355b7(67): Illuminate\View\View->render()
#6 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(37): include('/var/www/vhosts...')
#7 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/vhosts...', Array)
#8 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/var/www/vhosts...', Array)
#9 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#10 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#11 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#12 /var/www/vhosts/development/staging7/snipe-it/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#13 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#14 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#15 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#16 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#18 /var/www/vhosts/development/staging7/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#22 /var/www/vhosts/development/staging7/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#24 /var/www/vhosts/development/staging7/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#25 {main}

Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /var/www/vhosts/development/staging7/snipe-it/app/views/backend/layouts/default.blade.php) (View: /var/www/vhosts/development/staging7/snipe-it/app/views/backend/layouts/default.blade.php)' in /var/www/vhosts/development/staging7/snipe-it/app/storage/views/f3a02d09a768a44080912c422d274821:12
Stack trace:
#0 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/vhosts...', Array)
#2 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/var/www/vhosts...', Array)
#3 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /var/www/vhosts/development/staging7/snipe-it/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/vhosts/development/staging7/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/vhosts/development/staging7/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/vhosts/development/staging7/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /var/www/vhosts/development/staging7/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []
```

No errors in Apache errors log
-----

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 2.1.0
- What OS and web server you're running Snipe-IT on: Centos7 / Apache 2.4 (Behind a HAProxy)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual installation
- If you're getting an error in your browser, include that error (See above)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: / (which redirects to auth/signin)
- If a stacktrace is provided in the error, include that too. (See above)
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
No it isn't
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

**Comment by misilot** [comment]
Never mind, it was because the settings ID wasn't equal to 1. I forgot about this from the last time I tried snipe-it.

See: https://github.com/snipe/snipe-it/issues/858#issuecomment-115278694
