### ISSUE TITLE
Creating new asset: Column not found: 1054 Unknown column 'note' in 'field list' 

### ISSUE THREAD

**Issue by Th1990** [snipe/snipe-it#1924]
#### Expected Behavior 

New asset gets created and no error is displayed.

-----

#### Actual Behavior

New model asset does not get created and following error happens:
```
Illuminate \ Database \ QueryException (42S22)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'note' in 'field list' (SQL: insert into `models` (`depreciation_id`, `eol`, `name`, `modelno`, `manufacturer_id`, `category_id`, `note`, `user_id`, `updated_at`, `created_at`) values (0, 60, Test-asset, 1, 1, 5, , 1, 2016-04-06 08:54:27, 2016-04-06 08:54:27)) 
```

```
Open: /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php

    		}
     
    		// If an exception occurs when attempting to run a query, we'll format the error
    		// message to include the bindings with SQL, which will make this exception a
    		// lot more helpful to the developer instead of just the database's errors.
    		catch (\Exception $e)
    		{
    			throw new QueryException(
    				$query, $this->prepareBindings($bindings), $e
    			);
```
Seems to happen no matter what kind of asset model is being created and no matter what options are selected. Creating assets, licenceses and such seems to be working. I have only encountered this error when creating asset models.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v2.1.0-55
- What OS and web server you're running Snipe-IT on:
Ubuntu 14.04.4 LTS
Server version: Apache/2.4.7 (Ubuntu)

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc):
Install.sh. (Database was imported from other server with similar environment running Snipe-IT version v2.1.0, that installation had been done manually.)

- If you're getting an error in your browser, include that error:
If debug is false: "Oh no! Server Error: 500 (Internal Server Error)"
If debug true, the error given at the top of the post.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error:
hardware/models/create, pressing Save-button to create new asset model.

- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.
Only 500 Internal error

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
I could not reproduce the error in demo.

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
```
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'note' in 'field list' (SQL: insert into `models` (`depreciation_id`, `eol`, `name`, `modelno`, `manufacturer_id`, `category_id`, `note`, `user_id`, `updated_at`, `created_at`) values (0, 0, Test-asset, 1, 2, 1, , 1, 2016-04-06 09:06:32, 2016-04-06 09:06:32))' in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `mo...', Array, Object(Closure))
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `mo...', Array, Object(Closure))
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `mo...', Array)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `mo...', Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `mo...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1550): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1456): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/snipeit/app/controllers/admin/ModelsController.php(139): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: Controllers\Admin\ModelsController->postCreate()
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\ModelsController), Object(Illuminate\Routing\Route), 'postCreate')
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postCreate')
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#29 /var/www/snipeit/public/index.php(49): Illuminate\Foundation\Application->run()
#30 {main} [] []`
```

- Include what you've done so far in the installation, and if you got any error messages along the way.
Added models and assets manually. No erros before this. Exported database from other server.

- Indicate whether or not you've manually edited any data directly in the database
No manual editions.

**Comment by snipe** [comment]
Can you try running migrations? That field definitely exists if migrations have completed correctly.

**Comment by Th1990** [comment]
That fixed the problem.

```
**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? yes
Migrated: 2016_01_28_041048_add_notes_to_models
```
After this creating asset models works without errors.
