### ISSUE TITLE
Everything works except for those create buttons on Create Asset

### ISSUE THREAD

**Issue by MOD-LonnieJones** [snipe/snipe-it#1983]
#### Expected Behavior (or desired behavior if a feature request)

From Assets > List All > Create New > (Plus) Create new model

When clicking on the + button to add a new model, it will add a new model to the form.

---
#### Actual Behavior

Bug: From 'Create Asset', the Create model button doesn't work
Bug: From 'Create Asset', the Create status doesn't create
Bug: From 'Create Asset', the Create supplier button doesn't work
Bug: From 'Create Asset', the Create location button doesn't work

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:

**Version of Snipe-IT you're running**
v2.1.0-55
Windows Server 2016 Technical Preview 4- OS
IIS 10.0.10586
mariadb-10.0.24-winx64
PHPManagerForIIS-1.2.0-x64

**What method you used to install Snipe-IT**
Install via git clone

**If you're getting an error in your browser, include that error**
I've tried in Chrome, Edge, and IE.  It just doesn't do anything in the popup.

**What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error**
Assets > List All > Create New > (Plus) Create new model

**If a stacktrace is provided in the error, include that too.**

```
SCRIPT5007: Unable to get property 'error' of undefined or null reference create (759,7)
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier). (XHR): POST - https://192.168.1.24//api/models
```

**Any errors that appear in your browser's error console.**

In the demo it works correctly

**Include any additional information you can find in `app/storage/logs` and your webserver's logs.**

[2016-04-21 07:06:04] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 07:08:20] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 08:00:42] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 08:24:51] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 08:25:40] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 08:26:57] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 08:27:10] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 08:29:19] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 08:29:20] production.DEBUG: Local authentication: User dang not found [] []
[2016-04-21 08:29:27] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 08:29:27] production.DEBUG: Local authentication: User dang not found [] []
[2016-04-21 08:29:32] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 08:29:32] production.DEBUG: Local authentication: User dang not found [] []
[2016-04-21 08:30:15] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 08:38:22] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 08:45:17] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 08:46:35] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 09:31:33] production.ERROR: exception 'ErrorException' with message 'Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsTo::associate() must be an instance of Illuminate\Database\Eloquent\Model, null given, called in C:\inetpub\wwwroot\snipe-it\app\controllers\admin\AssetsController.php on line 104 and defined' in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\BelongsTo.php:203
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\BelongsTo.php(203): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', 'C:\inetpub\wwwr...', 203, Array)
#1 C:\inetpub\wwwroot\snipe-it\app\controllers\admin\AssetsController.php(104): Illuminate\Database\Eloquent\Relations\BelongsTo->associate(NULL)
#2 [internal function]: Controllers\Admin\AssetsController->postCreate()
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#4 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5847): Illuminate\Routing\Controller->callAction('postCreate', Array)
#5 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AssetsController), Object(Illuminate\Routing\Route), 'postCreate')
#6 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postCreate')
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}()
#8 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5398): call_user_func_array(Object(Closure), Array)
#9 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 C:\inetpub\wwwroot\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#14 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(7825): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#15 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#16 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#17 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(11118): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#18 C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#19 C:\inetpub\wwwroot\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#20 {main} [] []

[2016-04-21 09:33:05] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 09:33:13] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 09:36:51] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 09:37:14] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 09:40:13] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 09:40:24] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 09:40:24] production.DEBUG: Local authentication: User lonne-admin not found [] []
[2016-04-21 09:40:33] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 09:44:08] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 09:44:27] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 10:22:05] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 10:29:18] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 10:32:01] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 10:45:05] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 10:45:42] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 10:50:21] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 10:50:29] production.DEBUG: Authenticating user against database. [] []
[2016-04-21 10:52:21] production.DEBUG: Not logged in - admin-auth [] []
[2016-04-21 10:52:28] production.DEBUG: Authenticating user against database. [] []

**Include what you've done so far in the installation, and if you got any error messages along the way.**

I had received a few errors along the way.
- Composer removed the context menu feature.
- PHP Manager supports only up to IIS 9
- .NET 3.5 needs to be installed from an alternate source.
- Localhost page conflict
- Folder permissions for IIS users
- Snipe-IT forces HTTPS

**Indicate whether or not you've manually edited any data directly in the database**

I have a fresh install with minimal changes.

**Comment by snipe** [comment]
> Snipe-IT forces HTTPS

It doesn't, actually. You can remove the IIS URL rule to force SSL, and change the `url` key to use http instead of https in `app/config/production/app.php`

Can you tell me what you have listed for the `url` key there? My guess is that something's not right there, which is why it's trigger the 404, which is causing your issue.

**Comment by MOD-LonnieJones** [comment]
It was cool, I just made a certificate to make it go through.

For app.php, the line was previously:
'url' => 'http://localhost/',

I changed it to:
'url' => 'https://192.168.1.24/',

Then I added bindings for localhost and the IP.  I had tried switching the url line back and reset iss, but it made no difference. We have one user who is using it on and off today.

**Comment by snipe** [comment]
Please remove the trailing slash

**Comment by MOD-LonnieJones** [comment]
Nope, still nothing.  

I'm not sure if this is relevant.  When I tried to telnet in and it gives me a 404 error.

` HTTP/1.1 400 Bad Request
Content-Type: text/html; charset=us-ascii
Server: Microsoft-HTTPAPI/2.0
Date: Thu, 21 Apr 2016 22:53:38 GMT
Connection: close
Content-Length: 326

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Verb</h2>
<hr><p>HTTP Error 400. The request verb is invalid.</p>
</BODY></HTML>


Connection to host lost.`

 If I just go to the url through the browser, it will take me to the right place.  I'm thinking it is my connection to localhost.  I just looked it up and 127.0.0.1 is also not showing.

**Comment by snipe** [comment]
In your browser, can you access https://192.168.1.24//api/models or https://192.168.1.24/api/models?

If you're still getting a 404 there, it may be because of a network configuration issue.

**Comment by MOD-LonnieJones** [comment]
Yeah, I'm getting a 404 for both.

**Comment by snipe** [comment]
But yo access the site at https://192.168.1.24? You shouldn't be getting a 404 there, you should be getting a 500 error.

**Comment by MOD-LonnieJones** [comment]
Exactly! The rest of the site shouldn't be working, but it is. That's why I made a ticket.

-------- Original message --------

**Comment by snipe** [comment]
I honestly have no idea what could be going on here. Maybe try running `php composer.phar dump-autoload` to clear the routes? No one else is having this problem, so it's super weird that you are.

**Comment by remrat** [comment]
Was there ever a resolution to this issue?  I am experiencing the same problem.  I have ran php composer.phar dump-autoload but that did not correct my issue.

One item to note, is that I am accessing Snipe-IT via a subdirectory and not a new virtual host.  http://myserver.com/snipeit/public

I edited app.php to reflect this...
