### ISSUE TITLE
Large amount of stack trace exceptions in handler logs.

### ISSUE THREAD

**Issue by dbiers** [snipe/snipe-it#2179]
#### Expected Behavior 

Only have relevant information contained in the handler logs.

-----

#### Actual Behavior

Seems logs (located `app/storage/logs`) are getting spammed with the following (~20M each day).

```
[2016-06-01 06:50:53] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/vhosts/asset.domain.com/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:148
Stack trace:
#0 /var/www/vhosts/asset.domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1054): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/vhosts/asset.domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1022): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/vhosts/asset.domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/vhosts/asset.domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/vhosts/asset.domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/vhosts/asset.domain.com/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/vhosts/asset.domain.com/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/vhosts/asset.domain.com/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/vhosts/asset.domain.com/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/vhosts/asset.domain.com/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 /var/www/vhosts/asset.domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 /var/www/vhosts/asset.domain.com/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
```

-----
#### Please provide answers to these questions before posting your bug report:

- Version v2.1.0
- CentOS 7.x x64
- Combination of `install.sh` and manual.
- No browser errors.
- Unsure.  I just noticed this while running backups and it seemed it was taking a long time to copy log files.  This is when I discovered the log files were larger than they should be.
- Provided stack trace(s) above.
- Not seeing any.
- Unable to check demo server logs.

**Comment by snipe** [comment]
Can you tail the web server logs and tell me what page it's 404ing on?

**Comment by snipe** [comment]
Any update here?
