### ISSUE TITLE
Login after git pull and composer update not possible anymore

### ISSUE THREAD

**Issue by MPIAE-IT** [snipe/snipe-it#2243]
#### Expected Behavior (or desired behavior if a feature request)

Login should work
-----

#### Actual Behavior

Login is neither possible with local user nor ldap user
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **v3 (git pull from v3-master (7a4cbce))**
- What OS and web server you're running Snipe-IT on **Ubuntu Ubuntu 14.04 Apache 2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **manual**
- If you're getting an error in your browser, include that error

`ErrorException in AuthController.php line 94:
ldap_set_option(): supplied argument is not a valid ldap link resource`

`in AuthController.php line 94
at HandleExceptions->handleError('2', 'ldap_set_option(): supplied argument is not a valid ldap link resource', '/var/www/snipeit/app/Http/Controllers/Auth/AuthController.php', '94', array('username' => '***', 'password' => '***', 'returnUser' => false, 'ldaphost' => '***', 'ldaprdn' => '***@***', 'ldappass' => '***', 'baseDn' => 'DC=***', 'filterQuery' => 'samaccountname=***', 'ldapversion' => '3', 'ldap_server_cert_ignore' => '0', 'connection' => true))
at ldap_set_option(true, '8', '0') in AuthController.php line 94
at AuthController->ldap('***', '***') in AuthController.php line 211
at AuthController->login()
at call_user_func_array(array(object(AuthController), 'login'), array()) in compiled.php line 9419
at Controller->callAction('login', array()) in compiled.php line 9481
at ControllerDispatcher->call(object(AuthController), object(Route), 'login') in compiled.php line 9461
at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in RedirectIfAuthenticated.php line 24
at RedirectIfAuthenticated->handle(object(Request), object(Closure))
at call_user_func_array(array(object(RedirectIfAuthenticated), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in compiled.php line 9938
at Pipeline->then(object(Closure)) in compiled.php line 9462
at ControllerDispatcher->callWithinStack(object(AuthController), object(Route), object(Request), 'login') in compiled.php line 9449
at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\Auth\AuthController', 'login') in compiled.php line 8517
at Route->runController(object(Request)) in compiled.php line 8504
at Route->run(object(Request)) in compiled.php line 8218
at Router->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckLocale.php line 40
at CheckLocale->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckLocale), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 3225
at VerifyCsrfToken->handle(object(Request), object(Closure))
at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13139
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13076
at EncryptCookies->handle(object(Request), object(Closure))
at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in compiled.php line 9938
at Pipeline->then(object(Closure)) in compiled.php line 8219
at Router->runRouteWithinStack(object(Route), object(Request)) in compiled.php line 8210
at Router->dispatchToRoute(object(Request)) in compiled.php line 8200
at Router->dispatch(object(Request)) in compiled.php line 2419
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Debugbar.php line 49
at Debugbar->handle(object(Request), object(Closure))
at call_user_func_array(array(object(Debugbar), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TrustProxies.php line 46
at TrustProxies->handle(object(Request), object(Closure))
at call_user_func_array(array(object(TrustProxies), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForSetup), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))
at call_user_func_array(array(object(NosniffGuard), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in XssProtectHeader.php line 17
at XssProtectHeader->handle(object(Request), object(Closure))
at call_user_func_array(array(object(XssProtectHeader), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))
at call_user_func_array(array(object(FrameGuard), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13400
at ShareErrorsFromSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 11943
at StartSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 3286
at CheckForMaintenanceMode->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9953
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in compiled.php line 9938
at Pipeline->then(object(Closure)) in compiled.php line 2366
at Kernel->sendRequestThroughRouter(object(Request)) in compiled.php line 2350
at Kernel->handle(object(Request)) in index.php line 55`

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Login Page**
- If a stacktrace is provided in the error, include that too. -
- Any errors that appear in your browser's error console. -
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **No**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
laravel.log:
`[2016-07-11 17:40:32] production.DEBUG: LDAP is enabled.  
[2016-07-11 17:40:32] production.DEBUG: Auth lookup complete  
[2016-07-11 17:40:32] production.DEBUG: Local user *** exists in database. Authenticating existing user against LDAP.  
[2016-07-11 17:40:32] production.ERROR: exception 'ErrorException' with message 'ldap_set_option(): supplied argument is not a valid ldap link resource' in /var/www/snipeit/app/Http/Controllers/Auth/AuthController.php:94
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'ldap_set_option...', '/var/www/snipei...', 94, Array)
#1 /var/www/snipeit/app/Http/Controllers/Auth/AuthController.php(94): ldap_set_option(true, 8, 0)
#2 /var/www/snipeit/app/Http/Controllers/Auth/AuthController.php(211): App\Http\Controllers\Auth\AuthController->ldap('***', '***')
#3 [internal function]: App\Http\Controllers\Auth\AuthController->login()
#4 /var/www/snipeit/bootstrap/cache/compiled.php(9419): call_user_func_array(Array, Array)
#5 /var/www/snipeit/bootstrap/cache/compiled.php(9481): Illuminate\Routing\Controller->callAction('login', Array)
#6 /var/www/snipeit/bootstrap/cache/compiled.php(9461): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), 'login')
#7 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /var/www/snipeit/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/snipeit/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /var/www/snipeit/bootstrap/cache/compiled.php(9462): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /var/www/snipeit/bootstrap/cache/compiled.php(9449): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'login')
#18 /var/www/snipeit/bootstrap/cache/compiled.php(8517): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#19 /var/www/snipeit/bootstrap/cache/compiled.php(8504): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#20 /var/www/snipeit/bootstrap/cache/compiled.php(8218): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /var/www/snipeit/app/Http/Middleware/CheckLocale.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: App\Http\Middleware\CheckLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /var/www/snipeit/bootstrap/cache/compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /var/www/snipeit/bootstrap/cache/compiled.php(13139): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /var/www/snipeit/bootstrap/cache/compiled.php(13076): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/snipeit/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 /var/www/snipeit/bootstrap/cache/compiled.php(8219): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#46 /var/www/snipeit/bootstrap/cache/compiled.php(8210): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#47 /var/www/snipeit/bootstrap/cache/compiled.php(8200): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#48 /var/www/snipeit/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /var/www/snipeit/vendor/fideloper/proxy/src/TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#59 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 /var/www/snipeit/app/Http/Middleware/CheckForSetup.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#64 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#66 /var/www/snipeit/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 [internal function]: App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#69 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#71 /var/www/snipeit/app/Http/Middleware/XssProtectHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#74 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#76 /var/www/snipeit/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#77 [internal function]: App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#78 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#79 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#81 /var/www/snipeit/bootstrap/cache/compiled.php(13400): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#82 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#83 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#84 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#85 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#86 /var/www/snipeit/bootstrap/cache/compiled.php(11943): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#87 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#88 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#89 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#90 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#91 /var/www/snipeit/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#92 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#93 /var/www/snipeit/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#94 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#95 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#96 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#97 /var/www/snipeit/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#98 /var/www/snipeit/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#99 /var/www/snipeit/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#100 /var/www/snipeit/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#101 {main}  `
- Include what you've done so far in the installation, and if you got any error messages along the way. **Just tested it and everything was working fine. Just had some example date created and just started working with it**
- Indicate whether or not you've manually edited any data directly in the database - **NO**

**Comment by MPIAE-IT** [comment]
Just tried to clone into new directory and move the config files (.env) and folder (snipe-it/storage/app/backups/ snipe-it/storage/private_uploads/ snipe-it/public/uploads/).

also did composer install and update. Unfortunately the error is still appearing...

**Comment by veen1981** [comment]
Similar issue here. Just moved my server to an enterprise VM server, and thought the issue may have been related to the APP Key as speaking with Snipe yesterday in gitter. However logon will still work for me on my backed-up web directory from a week ago. As soon as I upgrade to the latest commit, logon breaks on both the new server and also on my old server.

**Comment by MPIAE-IT** [comment]
Oh OK. So I guess we have to wait for snipe to fix it. 👍

**Comment by veen1981** [comment]
So just for kicks, I installed a clean copy of Snipe-IT on a VM.

-Pulled latest V3-Master from github and ran the install script.
-Went through the web based flight check and created a user
-Added a couple generic models, suppliers, manufactures, etc.
-Manually created a user
-Then I added our companies LDAP settings and saved them.
-Logged out and attempted to log back in with the default user created in setup

Still getting the same error on logon with a brand new install of Snipe-IT and new DB.

**Comment by MPIAE-IT** [comment]
Thanks for your effort. I was about to try that as well, but you saved me a lot of time!

**Comment by MPIAE-IT** [comment]
Just made a git pull to the latest v3-master. Now it is working again. Thanks @snipe !

**Comment by MPIAE-IT** [comment]
OK I was a little hasty. Login with local user is possible now. But with AD User Login is not possible.

This is what I get from the log:

`[2016-07-14 10:24:14] production.DEBUG: LDAP is enabled.  
[2016-07-14 10:24:14] production.DEBUG: Local auth lookup complete  
[2016-07-14 10:24:14] production.DEBUG: Binding user to LDAP.  
[2016-07-14 10:24:14] production.DEBUG: Local user *** exists in database. Authenticating existing user against LDAP.  
[2016-07-14 10:24:14] production.DEBUG: User *** did not authenticate correctly against LDAP. Local user was not updated.  
[2016-07-14 10:24:14] production.DEBUG: Authenticating user against database.  
[2016-07-14 10:24:14] production.DEBUG: Local authentication failed.  
[2016-07-14 10:24:29] production.DEBUG: LDAP is enabled.  
[2016-07-14 10:24:29] production.DEBUG: Local auth lookup complete  
[2016-07-14 10:24:29] production.DEBUG: Binding user to LDAP.  
[2016-07-14 10:24:29] production.DEBUG: Local user ### exists in database. Authenticating existing user against LDAP.  
[2016-07-14 10:24:29] production.DEBUG: User ### did not authenticate correctly against LDAP. Local user was not updated.  
[2016-07-14 10:24:29] production.DEBUG: Authenticating user against database.  
`

**Comment by snipe** [comment]
Can you pull from v3 (not v3 master), rub migrations, and see if that fixes it? We unfortunately don't have an AD server to test against, only LDAP, so this info is SUPER helpful and we really appreciate it.

**Comment by snipe** [comment]
Grr. RUN migrations, not rub. Autocorrect hates me.

**Comment by MPIAE-IT** [comment]
I'm not so savvy with git commands. How do I change the the branch, git uses to pull? Right now I just do a `git pull`.
with migration you mean `php artisan migrate` ?!?

**Comment by veen1981** [comment]
I've testing this on VM, you can view my results under #2250

**Comment by MPIAE-IT** [comment]
Same here! With newest version (92175eb) V3-Master and new settings in LDAP Settings. Login is possible.
