### ISSUE TITLE
Error not reported when asset failed to create

### ISSUE THREAD

**Issue by ddreier** [snipe/snipe-it#2537]
Probably from restoring a backup, the `purchase_cost` column in my `assets` table got set to not allow NULLs. So when I tried to create a new asset the save/insert failed. But there was no feedback in the UI to show that there had been any error. 

#### Expected Behavior (or desired behavior if a feature request)

Show feedback in the UI that there was an issue saving the record to the database.

-----

#### Actual Behavior

Effectively the new asset page just reloaded clearing out all of information I had put into it. The error did make it into the log file, however, and that led me to the incorrect setting on that particular column.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 3.3.0-16-ge52a0f6
- What OS and web server you're running Snipe-IT on **Windows Server 2012 R2 w/ IIS 7.5**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **manual**
- If you're getting an error in your browser, include that error **N/A**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **/hardware/create**
- If a stacktrace is provided in the error, include that too.
```
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'purchase_cost' cannot be null (SQL: insert into `assets` (`model_id`, `name`, `serial`, `company_id`, `order_number`, `notes`, `asset_tag`, `user_id`, `archived`, `physical`, `depreciate`, `status_id`, `warranty_months`, `purchase_cost`, `purchase_date`, `assigned_to`, `supplier_id`, `requestable`, `rtd_location_id`, `updated_at`, `created_at`) values (58, , 6AZQ016050, , , On loan from Wacom, VS136, 2, 0, 1, 0, 1, , , , , 0, 0, 12, 2016-08-31 14:39:49, 2016-08-31 14:39:49))' in C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Database\Connection.php:729
Stack trace:
#0 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Database\Connection.php(685): Illuminate\Database\Connection->runQueryCallback('insert into `as...', Array, Object(Closure))
#1 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Database\Connection.php(458): Illuminate\Database\Connection->run('insert into `as...', Array, Object(Closure))
#2 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Database\Connection.php(414): Illuminate\Database\Connection->statement('insert into `as...', Array)
#3 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(32): Illuminate\Database\Connection->insert('insert into `as...', Array)
#4 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2082): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `as...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(1423): call_user_func_array(Array, Array)
#7 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(10862): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(10862): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(10851): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(10802): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 C:\inetpub\snipe-it-3\app\Http\Controllers\AssetsController.php(266): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: App\Http\Controllers\AssetsController->postCreate(Object(App\Http\Requests\AssetRequest))
#13 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9424): call_user_func_array(Array, Array)
#14 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9486): Illuminate\Routing\Controller->callAction('postCreate', Array)
#15 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9466): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\AssetsController), Object(Illuminate\Routing\Route), 'postCreate')
#16 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 C:\inetpub\snipe-it-3\app\Http\Middleware\Authenticate.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9467): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9454): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\AssetsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postCreate')
#27 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(8524): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'postCreate')
#28 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(8511): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#29 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(8225): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 C:\inetpub\snipe-it-3\app\Http\Middleware\CheckPermissions.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: App\Http\Middleware\CheckPermissions->handle(Object(Illuminate\Http\Request), Object(Closure), 'assets.create')
#34 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 C:\inetpub\snipe-it-3\app\Http\Middleware\Authenticate.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 C:\inetpub\snipe-it-3\app\Http\Middleware\CheckLocale.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: App\Http\Middleware\CheckLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#45 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(13212): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#55 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#57 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(13149): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#60 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#62 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#64 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(8226): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#65 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(8217): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#66 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(8207): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#67 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#68 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#69 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#70 C:\inetpub\snipe-it-3\vendor\fideloper\proxy\src\TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#71 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#73 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#75 C:\inetpub\snipe-it-3\app\Http\Middleware\CheckForSetup.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#76 [internal function]: App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#77 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#78 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#79 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#80 C:\inetpub\snipe-it-3\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#81 [internal function]: App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#83 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#85 C:\inetpub\snipe-it-3\app\Http\Middleware\XssProtectHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#86 [internal function]: App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#87 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#88 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#89 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#90 C:\inetpub\snipe-it-3\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#91 [internal function]: App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#92 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#93 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#94 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#95 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(13473): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#96 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#97 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#98 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#99 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#100 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(11963): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#101 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#102 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#103 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#104 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#105 C:\inetpub\snipe-it-3\vendor\misterphilip\maintenance-mode\src\MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode.php(145): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#106 [internal function]: MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#107 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#108 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#109 C:\inetpub\snipe-it-3\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#110 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#111 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#112 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#113 C:\inetpub\snipe-it-3\bootstrap\cache\compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#114 C:\inetpub\snipe-it-3\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#115 {main}  
```
- Any errors that appear in your browser's error console. **N/A**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **N/A**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. **See stacktrace**
- Include what you've done so far in the installation, and if you got any error messages along the way. **I already fixed the schema issue**
- Indicate whether or not you've manually edited any data directly in the database **It's possible ;)**

**Comment by snipe** [comment]
That should already be fixed on develop and will be out in the 3.4 release. (I have no idea how that constraint got added. I assume it was me, and I assume I had a good reason for it at the time, but it's dumb, so I fixed it.)

**Comment by snipe** [comment]
Meantime you can run `ALTER TABLE assets MODIFY purchase_cost DECIMAL(13,4) null;` to fix. (It won't break anything with a migration in 3.4 that does the same thing.)

**Comment by ddreier** [comment]
I looked though all of the migrations with "purchase_cost" in them, and they all looked correct. That leads me to believe that the bit got flipped when I restored a backup for whatever reason.

**Comment by snipe** [comment]
Yeah, I dunno. It's happened to a few people, and I'm not sure what happened, but at least that migration should fix it.

![weiners](https://cloud.githubusercontent.com/assets/197404/18146121/ef973d20-6f82-11e6-8204-db418782b8fb.gif)
