### ISSUE TITLE
exception 'BadMethodCallException' with message 'Method after does not exist.'

### ISSUE THREAD

**Issue by Dextro** [snipe/snipe-it#2582]
#### Expected Behavior (or desired behavior if a feature request)

a working Snipe-IT after upgrading from 2.1 to 3.4.
Migrations went well.

-----

#### Actual Behavior

[2016-09-08 09:15:48] production.ERROR: exception 'BadMethodCallException' with message 'Method after does not exist.' in /home/user/apps/inventory/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:74
Stack trace:
#0 /home/user/apps/inventory/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Routing\Router->__call('after', Array)
#1 /home/user/apps/inventory/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Routing\Router->after(Object(newrelic\Laravel\AfterFilter))
#2 /home/user/apps/inventory/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#3 /home/user/apps/inventory/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#4 /home/user/apps/inventory/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(232): Illuminate\Foundation\Application->bootstrapWith(Array)
#5 /home/user/apps/inventory/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(127): Illuminate\Foundation\Http\Kernel->bootstrap()
#6 /home/user/apps/inventory/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#7 /home/user/apps/inventory/public/index.php(60): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#8 {main}

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 3.4
- What OS and web server you're running Snipe-IT on: Debian 8.2 - Apache/2.4.10 - php 5.6.24
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): long time ago. I don't remember.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: /

- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by Dextro** [comment]
Problem solved.

Laravel 5.2 has issues (or the other way around) with the New Relic agent. Disabling the agent solves the problem.
