### ISSUE TITLE
Windows Upgrade Failure (3.2.0-53 to 3.5.0 beta)

### ISSUE THREAD

**Issue by howeluck** [snipe/snipe-it#2657]
#### Expected Behavior (or desired behavior if a feature request)

I expected the upgrade to be successful.

-----

#### Actual Behavior

Fails with these error(s):

FatalThrowableError in ProviderRepository.php line 146:
Class 'MisterPhilip\MaintenanceMode\MaintenanceModeServiceProvider' not found
in ProviderRepository.php line 146
at ProviderRepository->createProvider('MisterPhilip\MaintenanceMode\MaintenanceModeServiceProvider') in ProviderRepository.php line 114
at ProviderRepository->compileManifest(array('Illuminate\Auth\AuthServiceProvider', 'Illuminate\Broadcasting\BroadcastServiceProvider', 'Illuminate\Bus\BusServiceProvider', 'Illuminate\Cache\CacheServiceProvider', 'Illuminate\Foundation\Providers\ConsoleSupportServiceProvider', 'Illuminate\Cookie\CookieServiceProvider', 'Illuminate\Database\DatabaseServiceProvider', 'Illuminate\Encryption\EncryptionServiceProvider', 'Illuminate\Filesystem\FilesystemServiceProvider', 'Illuminate\Foundation\Providers\FoundationServiceProvider', 'Illuminate\Hashing\HashServiceProvider', 'Illuminate\Mail\MailServiceProvider', 'Illuminate\Pagination\PaginationServiceProvider', 'Illuminate\Pipeline\PipelineServiceProvider', 'Illuminate\Queue\QueueServiceProvider', 'Illuminate\Redis\RedisServiceProvider', 'Illuminate\Auth\Passwords\PasswordResetServiceProvider', 'Illuminate\Session\SessionServiceProvider', 'Illuminate\Translation\TranslationServiceProvider', 'Illuminate\Validation\ValidationServiceProvider', 'Illuminate\View\ViewServiceProvider', 'App\Providers\AppServiceProvider', 'App\Providers\AuthServiceProvider', 'App\Providers\EventServiceProvider', 'App\Providers\RouteServiceProvider', 'Barryvdh\Debugbar\ServiceProvider', 'Aws\Laravel\AwsServiceProvider', 'Intervention\Image\ImageServiceProvider', 'Collective\Html\HtmlServiceProvider', 'Spatie\Backup\BackupServiceProvider', 'Fideloper\Proxy\TrustedProxyServiceProvider', 'MisterPhilip\MaintenanceMode\MaintenanceModeServiceProvider', 'MisterPhilip\MaintenanceMode\MaintenanceCommandServiceProvider', 'App\Providers\MacroServiceProvider')) in ProviderRepository.php line 60
at ProviderRepository->load(array('Illuminate\Auth\AuthServiceProvider', 'Illuminate\Broadcasting\BroadcastServiceProvider', 'Illuminate\Bus\BusServiceProvider', 'Illuminate\Cache\CacheServiceProvider', 'Illuminate\Foundation\Providers\ConsoleSupportServiceProvider', 'Illuminate\Cookie\CookieServiceProvider', 'Illuminate\Database\DatabaseServiceProvider', 'Illuminate\Encryption\EncryptionServiceProvider', 'Illuminate\Filesystem\FilesystemServiceProvider', 'Illuminate\Foundation\Providers\FoundationServiceProvider', 'Illuminate\Hashing\HashServiceProvider', 'Illuminate\Mail\MailServiceProvider', 'Illuminate\Pagination\PaginationServiceProvider', 'Illuminate\Pipeline\PipelineServiceProvider', 'Illuminate\Queue\QueueServiceProvider', 'Illuminate\Redis\RedisServiceProvider', 'Illuminate\Auth\Passwords\PasswordResetServiceProvider', 'Illuminate\Session\SessionServiceProvider', 'Illuminate\Translation\TranslationServiceProvider', 'Illuminate\Validation\ValidationServiceProvider', 'Illuminate\View\ViewServiceProvider', 'App\Providers\AppServiceProvider', 'App\Providers\AuthServiceProvider', 'App\Providers\EventServiceProvider', 'App\Providers\RouteServiceProvider', 'Barryvdh\Debugbar\ServiceProvider', 'Aws\Laravel\AwsServiceProvider', 'Intervention\Image\ImageServiceProvider', 'Collective\Html\HtmlServiceProvider', 'Spatie\Backup\BackupServiceProvider', 'Fideloper\Proxy\TrustedProxyServiceProvider', 'MisterPhilip\MaintenanceMode\MaintenanceModeServiceProvider', 'MisterPhilip\MaintenanceMode\MaintenanceCommandServiceProvider', 'App\Providers\MacroServiceProvider')) in Application.php line 530
at Application->registerConfiguredProviders() in RegisterProviders.php line 17
at RegisterProviders->bootstrap(object(Application)) in Application.php line 203
at Application->bootstrapWith(array('Illuminate\Foundation\Bootstrap\DetectEnvironment', 'Illuminate\Foundation\Bootstrap\LoadConfiguration', 'Illuminate\Foundation\Bootstrap\ConfigureLogging', 'Illuminate\Foundation\Bootstrap\HandleExceptions', 'Illuminate\Foundation\Bootstrap\RegisterFacades', 'Illuminate\Foundation\Bootstrap\RegisterProviders', 'Illuminate\Foundation\Bootstrap\BootProviders')) in Kernel.php line 232
at Kernel->bootstrap() in Kernel.php line 127
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
at Kernel->handle(object(Request)) in index.php line 59

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

Version of Snipe-IT you're running
v3.2.0-53-gfff2bce attempting to update to 3.5.0 beta

What OS and web server you're running Snipe-IT on
Windows Server 2012 R2 - IIS web server

What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation

If you're getting an error in your browser, include that error
"Whoops, looks like something went wrong."

What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Loading the homepage (dashboard) or any other page.

If a stacktrace is provided in the error, include that too.
No stacktrace is provided.

Any errors that appear in your browser's error console.
The above error and also this:

ReflectionException in Container.php line 734:
Class MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode does not exist
in Container.php line 734
at ReflectionClass->__construct('MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode') in Container.php line 734
at Container->build('MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode', array()) in Container.php line 629
at Container->make('MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode', array()) in Application.php line 697
at Application->make('MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode') in Kernel.php line 152
at Kernel->terminate(object(Request), object(Response)) in index.php line 64

Confirm whether the error is reproduceable on the demo.
(see below in log)

Include any additional information you can find in app/storage/logs and your webserver's logs.
[2016-09-21 14:53:21] production.ERROR: ReflectionException: Class MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode does not exist in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php:734
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): ReflectionClass->__construct('MisterPhilip\\Ma...')
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Container\Container->build('MisterPhilip\\Ma...', Array)
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(697): Illuminate\Container\Container->make('MisterPhilip\\Ma...', Array)
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(152): Illuminate\Foundation\Application->make('MisterPhilip\\Ma...')
#4 C:\inetpub\wwwroot\snipe-it\public\index.php(64): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#5 {main} 

Include what you've done so far in the installation, and if you got any error messages along the way.
No errors

Indicate whether or not you've manually edited any data directly in the database
No

**Comment by dmeltzer** [comment]
You need to run composer install  with every update.

**Comment by howeluck** [comment]
@dmeltzer do you mean this?

```
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate
php artisan config:clear
php artisan config:cache
```

Because I did run this before attempting to overwrite the snipe-it installation with the files from 3.5.0-beta.

**Comment by snipe** [comment]
Thanks for the update
