### ISSUE TITLE
after login, show "your DocumentRoot is set incorrectly"

### ISSUE THREAD

**Issue by mikavio** [snipe/snipe-it#3333]
after login, it displayed "D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory. "

- [yes] I have enabled debug mode
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

- Version of Snipe-IT you're running
v3.6.3

- What OS and web server you're running Snipe-IT on
CentOS7,Apache2.4

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory. 

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
when accessing http://x.x.x.x(ip address)/login and after successing login, it displayed "D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory. "

- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.
only "D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory. "

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
It couldn't be occured on the demo.

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
#100 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#101 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#102 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#103 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#104 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#105 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#106 /var/www/html/snipeit/vendor/misterphilip/maintenance-mode/src/MisterPhilip/MaintenanceMode/Http/Middleware/CheckForMaintenanceMode.php(145): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#107 [internal function]: MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#108 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#109 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#110 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#111 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#112 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#113 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#114 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#115 /var/www/html/snipeit/public/index.php(59): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#116 {main}

- Include what you've done so far in the installation, and if you got any error messages along the way.
It displayed in error_log:
[Wed Feb 22 07:38:44.138240 2017] [authz_core:debug] [pid 3072] mod_authz_core.c(809): [client x.x.x.x:40685] AH01626: authorization result of <RequireAny>: granted, referer: http://x.x.x.x/login
[Wed Feb 22 07:38:45.040694 2017] [authz_core:debug] [pid 2953] mod_authz_core.c(809): [client x.x.x.x:40711] AH01626: authorization result of Require all granted: granted
[Wed Feb 22 07:38:45.040728 2017] [authz_core:debug] [pid 2953] mod_authz_core.c(809): [client x.x.x.x:40711] AH01626: authorization result of <RequireAny>: granted
[Wed Feb 22 07:41:45.078100 2017] [authz_core:debug] [pid 2952] mod_authz_core.c(809): [client x.x.x.x:42013] AH01626: authorization result of Require all granted: granted
[Wed Feb 22 07:41:45.078122 2017] [authz_core:debug] [pid 2952] mod_authz_core.c(809): [client x.x.x.x:42013] AH01626: authorization result of <RequireAny>: granted
[Wed Feb 22 07:41:45.078147 2017] [authz_core:debug] [pid 2952] mod_authz_core.c(809): [client x.x.x.x:42013] AH01626: authorization result of Require all granted: granted
[Wed Feb 22 07:41:45.078150 2017] [authz_core:debug] [pid 2952] mod_authz_core.c(809): [client x.x.x.x:42013] AH01626: authorization result of <RequireAny>: granted

- Indicate whether or not you've manually edited any data directly in the database
no

SElinux:disabled
httpd.conf:
NameVirtualHost x.x.x.x:80
Listen 80
<VirtualHost x.x.x.x>
Alias /snipeit "/var/www/html/snipeit/public"
        <Directory /var/www/html/snipeit/public>
                Require all granted
                AllowOverride All
                Options +Indexes
        </Directory>
        LogLevel debug
        DocumentRoot /var/www/html/snipeit/public
</VirtualHost>

**Comment by mikavio** [comment]
This problem was resolved.
http://x.x.x.x/index.php/ was the correct URL.
