### ISSUE TITLE
"php artisan clear-compiled" is Fatal 

### ISSUE THREAD

**Issue by rela1470** [snipe/snipe-it#3382]
#### Expected Behavior (or desired behavior if a feature request)

I want to Install Dependencies...
but, composer install is fatal error.
https://snipe-it.readme.io/docs/install-dependencies
-----

#### Actual Behavior

>su - nginx
>cd /var/httpdocs/
>git clone https://github.com/snipe/snipe-it
>cd snipe-it
>curl -sS https://getcomposer.org/installer | php
>php composer.phar install --no-dev --prefer-source

> php artisan clear-compiled
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /var/httpdocs/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /var/httpdocs/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log')
#1 /var/httpdocs/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array)
#2 /var/httpdocs/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
#3 /var/httpdocs/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): Illuminate\Foundation\Application->make('log')
#4 /var/httpdocs/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(804): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /var/httpdocs/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Container\Co in /var/httpdocs/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
Script php artisan clear-compiled handling the post-install-cmd event returned with error code 255

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
https://snipe-it.readme.io/docs/common-issues#section-fatal-error-uncaught-exception-reflectionexception-with-message-class-log-does-not-exist

I tred init .env

>rm -rf .env
>cp -a .env.example .env
>php composer.phar install --no-dev --prefer-source

.... same error!

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.4

- What OS and web server you're running Snipe-IT on

>cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core) 

>nginx -v
nginx version: nginx/1.10.2

>php -v
PHP 7.1.2 (cli) (built: Feb 15 2017 08:36:40) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

>php-fpm -v
PHP 7.1.2 (fpm-fcgi) (built: Feb 15 2017 08:39:14)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

>mysql --version
mysql  Ver 15.1 Distrib 5.5.52-MariaDB, for Linux (x86_64) using readline 5.1

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
git clone

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
can not

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
can not

- If a stacktrace is provided in the error, include that too.
can not

- Any errors that appear in your browser's error console.
can not

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
can not

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
empty

- Include what you've done so far in the installation, and if you got any error messages along the way.
empty

- Indicate whether or not you've manually edited any data directly in the database
empty

**Comment by rela1470** [comment]
I was missing install PDO.
>yum --enablerepo=remi-php71 install php-pdo
fixed! 

Can you add that to this document?
https://snipe-it.readme.io/docs/install-dependencies
