### ISSUE TITLE
Importer documentation: update required fields

### ISSUE THREAD

**Issue by rcarterv** [snipe/snipe-it#3932]
#### Expected Behavior (or desired behavior if a feature request)

I created a CSV file with fields matching the documentation found in the [v4.0 documentation](https://snipe-it.readme.io/v4.0/docs/importing). I only used the required fields. Navigate to https://snipeit_host/import and perform an import.

Expected behavior is that Assets will import with only the fields specified as required in the documentation.

-----

#### Actual Behavior

If I do not include the **Status** and **Model Number** field, I get this error in the laravel.log file:
```
[2017-09-07 09:16:33] production.ERROR: ErrorException: Undefined index: status_
id in /var/www/html/app/Importer/AssetImporter.php:66
```

At the time of writing this, the documentation lists Status as a not required field.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
**4.0 Beta 4**

- What OS and web server you're running Snipe-IT on
**Ubuntu 16.04 with Apache**

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**Docker**

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**https://snipeit_host/import**

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
**Log message displayed above**

- Include what you've done so far in the installation, and if you got any error messages along the way.
**No errors during install**

- Indicate whether or not you've manually edited any data directly in the database
**No manual edits in the database**

=======
I can work-around this problem by adding the Status and Model Number field, so I think it's just the doc that needs to be updated.

**Comment by snipe** [comment]
Thanks for the helpful info. We'll look into this. I am out of the country for a day or so, but maybe @dmeltzer can take a look. If not, I'll dive in when I'm stateside again.

**Comment by snipe** [comment]
Status and model number definitely shouldn't be required. Can you provide a few lines from a sample import (obfuscating any sensitive fields, of course) where you can reproduce this?

**Comment by snipe** [comment]
Also, what happens if you include a status, but no model number? (Any specific error messages would be really helpful here.)

**Comment by rcarterv** [comment]
Sure thing, here is the file I used:
```
Item Name,Company,Category,Model Name,Manufacturer,Asset Tag
est_asset,My Company,IA SS,AWS EC2,Amazon,SRV-1
```

And here is the full stack trace from the original file:
```
[2017-09-08 15:23:58] production.ERROR: ErrorException: Undefined index: status_
id in /var/www/html/app/Importer/AssetImporter.php:66
Stack trace:
#0 /var/www/html/app/Importer/AssetImporter.php(66): Illuminate\Foundation\Boots
trap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/html/a...'
, 66, Array)
#1 /var/www/html/app/Importer/AssetImporter.php(34): App\Importer\AssetImporter-
>createAssetIfNotExists(Array)
#2 /var/www/html/app/Importer/Importer.php(117): App\Importer\AssetImporter->han
dle(Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/Manag
esTransactions.php(29): App\Importer\Importer->App\Importer\{closure}(Object(Ill
uminate\Database\MySqlConnection))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManage
r.php(324): Illuminate\Database\Connection->transaction(Object(Closure))
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.
php(221): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#6 /var/www/html/app/Importer/Importer.php(124): Illuminate\Support\Facades\Faca
de::__callStatic('transaction', Array)
#7 /var/www/html/app/Http/Requests/ItemImportRequest.php(57): App\Importer\Impor
ter->import()
#8 /var/www/html/app/Http/Controllers/Api/ImportController.php(97): App\Http\Req
uests\ItemImportRequest->import(Object(App\Models\Import))
#9 [internal function]: App\Http\Controllers\Api\ImportController->process(Objec
t(App\Http\Requests\ItemImportRequest), '16')
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php
(55): call_user_func_array(Array, Array)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDisp
atcher.php(44): Illuminate\Routing\Controller->callAction('process', Array)
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203)
: Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Ro
ute), Object(App\Http\Controllers\Api\ImportController), 'process')
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160)
: Illuminate\Routing\Route->runController()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(559
): Illuminate\Routing\Route->run()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(3
0): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Ht
tp\Request))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authen
ticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object
(Illuminate\Http\Request))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(
148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Req
uest), Object(Closure), 'api')
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(5
3): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminat
e\Http\Request))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(
102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminat
e\Http\Request))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561
): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520
): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Rout
e), Object(Illuminate\Http\Request))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498
): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel
.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(3
0): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Obje
ct(Illuminate\Http\Request))
#25 /var/www/html/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Routing\
Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(
148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request),
 Object(Closure))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(5
3): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminat
e\Http\Request))
#28 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Ro
uting\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(
148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Obje
ct(Closure))
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(5
3): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminat
e\Http\Request))
#31 /var/www/html/app/Http/Middleware/CheckForSetup.php(27): Illuminate\Routing\
Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(
148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request),
 Object(Closure))
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(5
3): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminat
e\Http\Request))
#34 /var/www/html/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\P
ipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(
148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request),
Object(Closure))
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(5
3): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminat
e\Http\Request))
#37 /var/www/html/app/Http/Middleware/XssProtectHeader.php(17): Illuminate\Routi
ng\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(
148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Reques
t), Object(Closure))
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(5
3): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminat
e\Http\Request))
#40 /var/www/html/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pip
eline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(
148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Ob
ject(Closure))
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(5
3): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminat
e\Http\Request))
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareE
rrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closu
re}(Object(Illuminate\Http\Request))
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(
148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminat
e\Http\Request), Object(Closure))
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(5
3): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminat
e\Http\Request))
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/Sta
rtSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Obj
ect(Illuminate\Http\Request))
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(
148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\
Request), Object(Closure))
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(5
3): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminat
e\Http\Request))
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middle
ware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Ro
uting\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(
148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Obje
ct(Illuminate\Http\Request), Object(Closure))
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(5
3): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminat
e\Http\Request))
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(
102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminat
e\Http\Request))
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel
.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel
.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Il
luminate\Http\Request))
#55 /var/www/html/public/index.php(58): Illuminate\Foundation\Http\Kernel->handl
e(Object(Illuminate\Http\Request))
#56 {main}
```

**Comment by rcarterv** [comment]
When I add a 'status' field like this:
```
Item Name,Company,Category,Model Name,Manufacturer,Asset Tag,Status
est_asset,My Company,IA SS,AWS EC2,Amazon,SRV-1,Pending
```

I see this error in the web console:
```
Warning Some Errors occured while importing

Item | Errors
AWS EC2 | Asset Model "AWS EC2": The model number must be at least 1 characters.


```

**Comment by snipe** [comment]
That's very helpful, thank you! (This was a pretty big rewrite of the importer, so these use-cases are invaluable to us.)

**Comment by snipe** [comment]
https://github.com/snipe/snipe-it/commit/6c283de60a965c42d866690047f087a3618afbac *might* help with the status_id part - still looking into the model number business.

**Comment by snipe** [comment]
@dmeltzer did the changes you made recently address the model number issue?
