### ISSUE TITLE
API key unauthorized after upgrade from v4-beta6

### ISSUE THREAD

**Issue by ghaberek** [snipe/snipe-it#4008]
I was not able to use my existing API key from beta6 after I upgraded to v4 proper. Generated a new key and that works fine. Should I have expected the previous key to continue working? I don't need this fixed but it seemed relevant to log an issue.

-----
#### Expected Behavior (or desired behavior if a feature request)

Expected API to continue working.

-----
#### Actual Behavior

Get following response when using old key.

    # export DEVELOPMENT_KEY=mykeygoeshere
    # curl -s -X GET -H "Accept: application/json" -H "Authorization: Bearer $DEVELOPMENT_KEY" "http://snipeitv4.mydomain.local/api/v1/categories/1" | python -m json.tool
    {
        "error": "Unauthorized."
    }

Log states `The resource owner or authorization server denied the request.` See below.

-----
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode (_would this help with API issues?_)
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running `v4.0 build 1 (g998c4a5)`
- What OS and web server you're running Snipe-IT on `CentOS Linux release 7.4.1708`, `Apache 2.4.6`
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) `manual install via zip file download`
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error `N/A`
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error `any call to the API`
- If a stacktrace is provided in the error, include that too. `see below`
- Any errors that appear in your browser's error console. `N/A`
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). `N/A`
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. `see below`
- Include what you've done so far in the installation, and if you got any error messages along the way. `upgrade from v4-beta6 to v4 went fine, no errors`
- Indicate whether or not you've manually edited any data directly in the database `no`

----

```
[2017-09-25 15:25:31] production.ERROR: exception 'League\OAuth2\Server\Exception\OAuthServerException' with message 'The resource owner or authorization server denied the request.' in /var/www/html/snipeit/vendor/league/oauth2-server/src/Exception/OAuthServerException.php:168
Stack trace:
#0 /var/www/html/snipeit/vendor/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php(53): League\OAuth2\Server\Exception\OAuthServerException::accessDenied('Access token co...')
#1 /var/www/html/snipeit/vendor/league/oauth2-server/src/ResourceServer.php(82): League\OAuth2\Server\AuthorizationValidators\BearerTokenValidator->validateAuthorization(Object(Zend\Diactoros\ServerRequest))
#2 /var/www/html/snipeit/vendor/laravel/passport/src/Guards/TokenGuard.php(110): League\OAuth2\Server\ResourceServer->validateAuthenticatedRequest(Object(Zend\Diactoros\ServerRequest))
#3 /var/www/html/snipeit/vendor/laravel/passport/src/Guards/TokenGuard.php(90): Laravel\Passport\Guards\TokenGuard->authenticateViaBearerToken(Object(Illuminate\Http\Request))
#4 /var/www/html/snipeit/vendor/laravel/passport/src/PassportServiceProvider.php(255): Laravel\Passport\Guards\TokenGuard->user(Object(Illuminate\Http\Request))
#5 [internal function]: Laravel\Passport\PassportServiceProvider->Laravel\Passport\{closure}(Object(Illuminate\Http\Request))
#6 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Auth/RequestGuard.php(55): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#7 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(49): Illuminate\Auth\RequestGuard->user()
#8 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(61): Illuminate\Auth\RequestGuard->check()
#9 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(41): Illuminate\Auth\Middleware\Authenticate->authenticate(Array)
#10 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#11 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#15 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#16 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/html/snipeit/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/html/snipeit/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/html/snipeit/app/Http/Middleware/CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/html/snipeit/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/html/snipeit/app/Http/Middleware/XssProtectHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/html/snipeit/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#48 /var/www/html/snipeit/public/index.php(59): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
```

**Comment by snipe** [comment]
Hm, that *is* weird. Although if you re-ran passport-install, that might explain it, since I think that command (it's a laravel built-in command) doesn't check for existing keys, it just generates new ones.

**Comment by snipe** [comment]
I'll make a note in the installation instructions to NOT re-run passport:install if you've already run it. I may also write a wrapper artisan command that at least checks if the keys already exist, and only runs them if it doesn't.

**Comment by ghaberek** [comment]
This happened again when I pulled the latest `master` to get your fixes to the groups API endpoint (thanks, BTW). Here are the *exact* commands I ran to upgrade from `v4.0 build1` to current `master`. Did I somehow run `passport:install` indirectly? I'm not too familiar with composer, artisan, or laravel at this point.

    mv -v snipe-it/ snipe-it-v4.0-build1/
    git clone https://github.com/snipe/snipe-it.git snipe-it
    cp -vp snipe-it-v4.0-build1/.env snipe-it/
    cp -vp snipe-it-v4.0-build1/public/uploads/models/*.jpg snipe-it/public/uploads/models/
    chown -vR apache:apache snipe-it/
    cd snipe-it/
    curl -sS https://getcomposer.org/installer | php
    php composer.phar install --no-dev --prefer-source
    php composer.phar dump-autoload
    php artisan view:clear
    php artisan cache:clear
    php artisan config:clear
    php artisan migrate

Same message in the laravel.log file:

    [2017-09-28 09:36:32] production.ERROR: exception 'League\OAuth2\Server\Exception\OAuthServerException' with message 'The resource owner or authorization server denied the request.' in /var/www/html/snipe-it/vendor/league/oauth2-server/src/Exception/OAuthServerException.php:168

**Comment by glureau** [comment]
I have the same issue after using `php artisan migrate` (new version: v4.1.3 build 48 (g74aa562) )
Have you find a way to fix it?

**Comment by dmeltzer** [comment]
It doesn't look like you copied over your oauth keys from the initial install.  shoudl be storage/oauth*.key
