### ISSUE TITLE
Import failure with both GUI and CLI

### ISSUE THREAD

**Issue by tosterbe** [snipe/snipe-it#4107]
#### Expected Behavior (or desired behavior if a feature request)

GUI import of sample data set (CSV) should be successful.
CLI import of sample data set (CSV) should be successful.

Sample CSV data harvested from snippet WWW site.

-----

#### Actual Behavior

Import via UI hangs following clicking 'import' button once green 'processing' object is displayed.   Import via CLI of test CSV data from snipe-it WWW site fails.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 

Fresh install

- Version of Snipe-IT you're running

4.0.6 Build 47
- Version of PHP you're running

7.0

- Version of MySQL/MariaDB you're running

mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- What OS and web server you're running Snipe-IT on

Debian 9 // apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

manual

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
<img width="1312" alt="snipeit-cli" src="https://user-images.githubusercontent.com/22563153/31083751-608abfc8-a747-11e7-8846-f747d9a61ab1.png">
<img width="1315" alt="snipeit-errors1" src="https://user-images.githubusercontent.com/22563153/31083753-60984044-a747-11e7-96fe-79a176e678bb.png">

- Any errors that appear in your browser's error console.

See attached pic for GUI.

CLI:

labuser@inventory:/var/www/snipeit$ php artisan snipeit:import snipe-sample-assets.csv --verbose

  [Symfony\Component\Console\Exception\InvalidArgumentException]
  The "testrun" option does not exist.

Exception trace:
 () at /var/www/snipeit/vendor/symfony/console/Input/Input.php:158
 Symfony\Component\Console\Input\Input->getOption() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php:276
 Illuminate\Console\Command->option() at /var/www/snipeit/app/Console/Commands/ObjectImportCommand.php:81
 App\Console\Commands\ObjectImportCommand->fire() at n/a:n/a
 call_user_func_array() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:531
 Illuminate\Container\Container->call() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
 Illuminate\Console\Command->execute() at /var/www/snipeit/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /var/www/snipeit/vendor/symfony/console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /var/www/snipeit/vendor/symfony/console/Application.php:228
 Symfony\Component\Console\Application->doRun() at /var/www/snipeit/vendor/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/snipeit/artisan:35

- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.

Import is disabled in demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

**from importer.log:**

[2017-10-02 14:51:39] production.ERROR: Symfony\Component\Console\Exception\InvalidArgumentException: The "testrun" option does not exist. in /var/www/snipeit/vendor/symfony/console/Inpu
t/Input.php:158
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(276): Symfony\Component\Console\Input\Input->getOption('testrun')
#1 /var/www/snipeit/app/Console/Commands/ObjectImportCommand.php(81): Illuminate\Console\Command->option('testrun')
#2 [internal function]: App\Console\Commands\ObjectImportCommand->fire()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Ar
ray, Object(Closure))
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array,
NULL)
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#8 /var/www/snipeit/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\Outp
utStyle))
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Ob
ject(Illuminate\Console\OutputStyle))
#10 /var/www/snipeit/vendor/symfony/console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Outp
ut\ConsoleOutput))
#11 /var/www/snipeit/vendor/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\ObjectImportCommand), Object(Symfony\Com
ponent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/snipeit/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component
\Console\Output\ConsoleOutput))
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInp
ut), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 {main}
labuser@inventory:/var/www/snipeit/storage/logs$

**last block from laravel.log**

[2017-10-02 14:51:39] production.ERROR: Symfony\Component\Console\Exception\InvalidArgumentException: The "testrun" option does not exist. in /var/www/snipeit/vendor/symfony/console/Inpu
t/Input.php:158
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(276): Symfony\Component\Console\Input\Input->getOption('testrun')
#1 /var/www/snipeit/app/Console/Commands/ObjectImportCommand.php(81): Illuminate\Console\Command->option('testrun')
#2 [internal function]: App\Console\Commands\ObjectImportCommand->fire()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Ar
ray, Object(Closure))
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array,
NULL)
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#8 /var/www/snipeit/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\Outp
utStyle))
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Ob
ject(Illuminate\Console\OutputStyle))
#10 /var/www/snipeit/vendor/symfony/console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Outp
ut\ConsoleOutput))
#11 /var/www/snipeit/vendor/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\ObjectImportCommand), Object(Symfony\Com
ponent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/snipeit/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component
\Console\Output\ConsoleOutput))
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInp
ut), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 {main}

- Include what you've done so far in the installation, and if you got any error messages along the way.

Aside from expected errors such as missing dependencies, nothing out of the ordinary displayed.

- Indicate whether or not you've manually edited any data directly in the database

No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by tosterbe** [comment]
Should have read a bit before I posted..

Looks to be a dupe of #4077
