### ISSUE TITLE
Checking out a new asset from the asset creation screen (/hardware/create) to another asset causes ErrorException: Undefined index: next_audit_date

### ISSUE THREAD

**Issue by pako-pl** [snipe/snipe-it#4711]
#### Expected Behavior (or desired behavior if a feature request)

Checking out a new asset from the asset creation screen (/hardware/create) to another asset doesn't work.

-----

#### Actual Behavior

The new asset gets created, but it is not checked out to the selected asset. I have to checkout it later - then it works properly.

An exception is thrown (I attached the stack trace below): `production.ERROR: ErrorException: Undefined index: next_audit_date in /snipe-it/www/app/Observers/AssetObserver.php:49`

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Version v4.1.9 - build 3128 (master)
- PHP 7.1.12
- MySQL 5.7.20
- Manual installation
- There are no errors in the browser console.
- The issue is not reproducible on the demo: https://snipeitapp.com/demo (everything works correctly there)
- Stack trace from laravel.log:

```
[2017-12-31 00:20:56] production.ERROR: ErrorException: Undefined index: next_audit_date in /snipe-it/www/app/Observers/AssetObserver.php:49
Stack trace:
#0 /snipe-it/www/app/Observers/AssetObserver.php(49): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/snipe-it/...', 49, Array)
#1 [internal function]: App\Observers\AssetObserver->updating(Object(App\Models\Asset))
#2 /snipe-it/www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(367): call_user_func_array(Array, Array)
#3 /snipe-it/www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(199): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('eloquent.updati...', Array)
#4 /snipe-it/www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(159): Illuminate\Events\Dispatcher->dispatch('eloquent.updati...', Array, true)
#5 /snipe-it/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(148): Illuminate\Events\Dispatcher->until('eloquent.updati...', Object(App\Models\Asset))
#6 /snipe-it/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(578): Illuminate\Database\Eloquent\Model->fireModelEvent('updating')
#7 /snipe-it/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(515): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder))
#8 /snipe-it/www/app/Models/Asset.php(185): Illuminate\Database\Eloquent\Model->save()
#9 /snipe-it/www/app/Http/Controllers/AssetsController.php(236): App\Models\Asset->checkOut(Object(App\Models\Asset), Object(App\Models\User), '2017-12-31 00:2...', '', 'Checked out on ...', '', 7)
#10 [internal function]: App\Http\Controllers\AssetsController->store(Object(App\Http\Requests\AssetRequest))
#11 /snipe-it/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#12 /snipe-it/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('store', Array)
#13 /snipe-it/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\AssetsController), 'store')
#14 /snipe-it/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#15 /snipe-it/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#16 /snipe-it/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
[...]
```

I checked that the database contains the `asset.next_audit_date` field. Checking out works correctly when I do it after creating the asset.

**Comment by pako-pl** [comment]
Similar bug report: https://github.com/snipe/snipe-it/issues/4652
