### ISSUE TITLE
Asset Import Issues

### ISSUE THREAD

**Issue by marsh3gbsd** [snipe/snipe-it#4977]
#### Expected Behavior (or desired behavior if a feature request)

Import CSV of assets, and have processing complete with assets added to database.

-----

#### Actual Behavior

Select Import File -> Success
Process -> Change to Assets -> Import -> Hang on Processing

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
**Fresh Install**
- Version of Snipe-IT you're running
**v4.1.11-pre - build 3307 (master)**
- Version of PHP you're running
**7.1.13**
- Version of MySQL/MariaDB you're running
**5.5.56**
- What OS and web server you're running Snipe-IT on
**Centos 7-4.1708.el7 / Apache 2.4.6**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
```
[16:56:04] LOG.error: InvalidArgumentException: Use a flat array with unique string values in /var/www/html/snipeit/vendor/league/csv/src/Reader.php:290
```

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**Import Page->Process File>Import**
- If a stacktrace is provided in the error, include that too. 
```
Stack trace:
#0 /var/www/html/snipeit/vendor/league/csv/src/Reader.php(269): League\Csv\Reader->validateKeys(Array)
#1 /var/www/html/snipeit/vendor/league/csv/src/Reader.php(235): League\Csv\Reader->getAssocKeys(0)
#2 /var/www/html/snipeit/app/Importer/Importer.php(111): League\Csv\Reader->fetchAssoc()
#3 /var/www/html/snipeit/app/Http/Requests/ItemImportRequest.php(57): App\Importer\Importer->import()
#4 /var/www/html/snipeit/app/Http/Controllers/Api/ImportController.php(100): App\Http\Requests\ItemImportRequest->import(Object(App\Models\Import))
#5 [internal function]: App\Http\Controllers\Api\ImportController->process(Object(App\Http\Requests\ItemImportRequest), '9')
#6 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#7 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('process', Array)
#8 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\ImportController), 'process')
#9 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#10 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#11 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#14 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#18 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#19 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/html/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/html/snipeit/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/html/snipeit/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/html/snipeit/app/Http/Middleware/CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/html/snipeit/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/html/snipeit/app/Http/Middleware/ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/html/snipeit/app/Http/Middleware/ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/html/snipeit/app/Http/Middleware/XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/html/snipeit/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#59 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#60 /var/www/html/snipeit/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#61 {main}**
```
- Any errors that appear in your browser's error console.
```
POST http://10.89.201.35/api/v1/imports/process/9 500 (Internal Server Error)
(anonymous) @ all.js?id=722d1692756a30dc1ece:10
s @ all.js?id=722d1692756a30dc1ece:9
vt @ all.js?id=722d1692756a30dc1ece:10
F @ all.js?id=722d1692756a30dc1ece:9
l @ all.js?id=722d1692756a30dc1ece:10
u @ all.js?id=722d1692756a30dc1ece:10
ft @ all.js?id=722d1692756a30dc1ece:10
l @ all.js?id=722d1692756a30dc1ece:10
u @ all.js?id=722d1692756a30dc1ece:10
gt @ all.js?id=722d1692756a30dc1ece:10
l @ all.js?id=722d1692756a30dc1ece:10
u @ all.js?id=722d1692756a30dc1ece:10
pt @ all.js?id=722d1692756a30dc1ece:10
l @ all.js?id=722d1692756a30dc1ece:10
u @ all.js?id=722d1692756a30dc1ece:10
ht @ all.js?id=722d1692756a30dc1ece:9
l @ all.js?id=722d1692756a30dc1ece:10
u @ all.js?id=722d1692756a30dc1ece:10
ct @ all.js?id=722d1692756a30dc1ece:9
l @ all.js?id=722d1692756a30dc1ece:10
u @ all.js?id=722d1692756a30dc1ece:10
mt @ all.js?id=722d1692756a30dc1ece:10
l @ all.js?id=722d1692756a30dc1ece:10
u @ all.js?id=722d1692756a30dc1ece:10
ut @ all.js?id=722d1692756a30dc1ece:9
l @ all.js?id=722d1692756a30dc1ece:10
u @ all.js?id=722d1692756a30dc1ece:10
(anonymous) @ all.js?id=722d1692756a30dc1ece:10
l @ all.js?id=722d1692756a30dc1ece:10
(anonymous) @ all.js?id=722d1692756a30dc1ece:10
s @ all.js?id=722d1692756a30dc1ece:9
e @ all.js?id=722d1692756a30dc1ece:10
z @ all.js?id=722d1692756a30dc1ece:9
z.(anonymous function) @ all.js?id=722d1692756a30dc1ece:10
postSave @ all.js?id=722d1692756a30dc1ece:21
i @ all.js?id=722d1692756a30dc1ece:4
e @ all.js?id=722d1692756a30dc1ece:5
```

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
**Cannot test import on demo**
- Include any additional information you can find in `storage/logs` and your webserver's logs. 
**No entries in webserver logs since start.  Laravel log contains the stacktrace above.**
- Include what you've done so far in the installation, and if you got any error messages along the way. 
**No error messages.  Clean install of CentOS, run install.sh to get snipe-it running**
- Indicate whether or not you've manually edited any data directly in the database 
**No manual editing**

Trimmed/anonymized CSV that is presenting this issue attached (zipped for github compatibility).
[Asset_exportmin.zip](https://github.com/snipe/snipe-it/files/1700983/Asset_exportmin.zip)

**Comment by blackrandom** [comment]
That error indicates you have a repeating field in your header.
I looked at your csv and it looks like the field 'Manufacturer' is repeated. Try adjusting it and see if it fixes the issue.

**Comment by marsh3gbsd** [comment]
Gah, that was the issue.  The import worked great with the duplicate field removed.  Thanks!
