### ISSUE TITLE
Delete asset : Trying to get property of non-object

### ISSUE THREAD

**Issue by benunter** [snipe/snipe-it#534]
On v1.2.5, when accessing hardware?Deleted=true page, I get a HTTP 500 error. In the logs, I have the following exceptions (it could be related to #530 issue).

```
[2015-02-18 09:49:06] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/snipeit/app/storage/views/c975b5d88ab791700b7675320438d0d2:95
Stack trace:
#0 /var/www/snipeit/app/storage/views/c975b5d88ab791700b7675320438d0d2(95): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/snipei...', 95, Array)
#1 /var/www/snipeit/bootstrap/compiled.php(9830): include('/var/www/snipei...')
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/snipei...', Array)
#3 /var/www/snipeit/bootstrap/compiled.php(9708): Illuminate\View\Engines\CompilerEngine->get('/var/www/snipei...', Array)
#4 /var/www/snipeit/bootstrap/compiled.php(9695): Illuminate\View\View->getContents()
#5 /var/www/snipeit/bootstrap/compiled.php(9686): Illuminate\View\View->renderContents()
#6 /var/www/snipeit/bootstrap/compiled.php(10388): Illuminate\View\View->render()
#7 /var/www/snipeit/bootstrap/compiled.php(9918): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#8 /var/www/snipeit/bootstrap/compiled.php(5222): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#9 /var/www/snipeit/bootstrap/compiled.php(5030): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#10 /var/www/snipeit/bootstrap/compiled.php(5016): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 /var/www/snipeit/bootstrap/compiled.php(721): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/snipeit/bootstrap/compiled.php(702): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/snipeit/bootstrap/compiled.php(7779): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/snipeit/bootstrap/compiled.php(8386): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/snipeit/bootstrap/compiled.php(8333): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/snipeit/bootstrap/compiled.php(10992): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/snipeit/bootstrap/compiled.php(664): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#19 /var/www/snipeit/public/index.php(49): Illuminate\Foundation\Application->run()
#20 {main}

Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /var/www/snipeit/app/views/backend/hardware/index.blade.php)' in /var/www/snipeit/app/storage/views/c975b5d88ab791700b7675320438d0d2:95
Stack trace:
#0 /var/www/snipeit/bootstrap/compiled.php(9832): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/snipei...', Array)
#2 /var/www/snipeit/bootstrap/compiled.php(9708): Illuminate\View\Engines\CompilerEngine->get('/var/www/snipei...', Array)
#3 /var/www/snipeit/bootstrap/compiled.php(9695): Illuminate\View\View->getContents()
#4 /var/www/snipeit/bootstrap/compiled.php(9686): Illuminate\View\View->renderContents()
#5 /var/www/snipeit/bootstrap/compiled.php(10388): Illuminate\View\View->render()
#6 /var/www/snipeit/bootstrap/compiled.php(9918): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/snipeit/bootstrap/compiled.php(5222): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /var/www/snipeit/bootstrap/compiled.php(5030): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /var/www/snipeit/bootstrap/compiled.php(5016): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/snipeit/bootstrap/compiled.php(721): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/snipeit/bootstrap/compiled.php(702): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/snipeit/bootstrap/compiled.php(7779): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/snipeit/bootstrap/compiled.php(8386): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/snipeit/bootstrap/compiled.php(8333): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/snipeit/bootstrap/compiled.php(10992): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/snipeit/bootstrap/compiled.php(664): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /var/www/snipeit/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []
```

**Comment by snipe** [comment]
Did you upgrade, or is this a new install with 1.2.5?

**Comment by snipe** [comment]
There was an error in the db seed data prior to version 1.2.5, so if you downloaded the files and seeded the database before 1.2.5, you should re-seed (assuming no production data exists)

**Comment by benunter** [comment]
I upgraded and I already have production data. I try to seed in a second database and reimport my production data and give you feedback if it succeed.

**Comment by benunter** [comment]
I fixed the problem. In fact, a missing model for one deleted asset was the reason of the exception, so the issue can be closed.

**Comment by elisiano** [comment]
This systematically happens every time I upgrade.
First time from v1.1 to v1.2.5. Then, thinking we skipped too many versions, we decided to start from scratch, seed the db with the examples (otherwise it doesn't work) and at that point everything was fine.
We did our housekeeping (i.e.: delete the examples and fill in our assets) and then again we migrated from 1.2.5 to 1.2.6 and it happened again.

Is there anyway to fix this?

I don't kno

**Comment by snipe** [comment]
@elisiano The problem was with older seed data, so if the old seed data is still in there (though marked as deleted), you could potentially still see this problem. Can you manually delete the seed records?

**Comment by elisiano** [comment]
That's exactly what we did and the problem went away.
Thanks for confirming.

**Comment by snipe** [comment]
@elisiano Great, I apologize for the frustration. We didn't realize the error in the seed data until recently (and then we fixed it).

![xy2ie](https://cloud.githubusercontent.com/assets/197404/6537200/37da3942-c409-11e4-82e0-7226d02bcc5a.gif)
