### ISSUE TITLE
error 500 snipe it

### ISSUE THREAD

**Issue by elpijitigakilo** [snipe/snipe-it#5379]
hi, 

i follow this link https://www.vultr.com/docs/how-to-install-snipe-it-on-centos-7 to install snipe it on centos7. 
but error 500 still hapen.. please help..

thanks before

**Comment by EarlRamirez** [comment]
@elpijitigakilo I would recommend that you use the following link **https://snipe-it.readme.io/docs/installation** to install snipe, the link you use, I will not recommend for a few reasons, the document root is none standard and SELinux will complain, you must never run composer as root and sudo composer.phar is not something you want to do.

**Comment by elpijitigakilo** [comment]
@EarlRamirez ok, so it's only installation snipeit and composer we may not using root and sudo? 
but for another installation (PHP, mariaDB, system upddate, apache), can we use root and sudo?

**Comment by EarlRamirez** [comment]
@elpijitigakilo you can install all the packages and composer as sudo/root; however, you should not run composer as root. **https://snipe-it.readme.io/docs/installation** is very detailed, basically, you need to clone the repository ==> here **https://snipe-it.readme.io/docs/downloading**, navigate to the directory and run **sudo ./install.sh**, you will be prompt for a few inputs; however, it will do the majority of the work for you, including installing and configuration of Apache web server and SELinux. Then follow the docs here ==>**https://snipe-it.readme.io/docs/configuration**. Let me know if this helps

**Comment by elpijitigakilo** [comment]
why you @snipe close my ticket? 
@EarlRamirez ok i will try, and update to you again.

**Comment by snipe** [comment]
@elpijitigakilo I closed it because @EarlRamirez answered you.

**Comment by snipe** [comment]
@elpijitigakilo You can update the ticket if you have additional issues - however you went out of your way to delete the questions we put in the issue template. We're not going to be able to help you without that information.

**Comment by elpijitigakilo** [comment]
not solve.. i mean that is not detail information where we can install the snipe it .. 
so we'll missed of best installation and configuration snipeit. 
and snipeit not give me detail information about apache and selinux installation.. just info apache and selinux. 

yes i know this is free, but it's wasting time to learn snipeit..  :-(

**Comment by EarlRamirez** [comment]
@elpijitigakilo what are the challenges you are experiencing with the installation? I agree totally with @snipe for closing the issue because you fail to provide crucial information. The instructions are clear and as mentioned previously you need to download "clone" Snipe-IT and run ./install.sh and it will do the heavy lifting for you.

Respond with your challenges and I will do my best to help you.

**Comment by elpijitigakilo** [comment]
i do appreciate for your help. 
ok l'll brake down of my work and please correct me if i'm wrong. 

1. running all component based on this link https://www.vultr.com/docs/how-to-install-snipe-it-on-centos-7 from step 1 until step 5 and running with root/sudo user. right?

2. on step 6, running below command with user only (not root or administrator user)
    cd ~
    curl -sS https://getcomposer.org/installer | php
    sudo mv composer.phar /usr/bin/composer

3. and running clone the repository ==> here https://snipe-it.readme.io/docs/downloading, navigate to the directory and run sudo ./install.sh, (and do with my work)

4. and running all configuration ==> https://snipe-it.readme.io/docs/configuration. 

my question is, 
1.  when i clone/install snipe it (on third step), where i navigate the path? on "/var/www/snipeit" or default "cd~"  ?
2.  i use centos7 latest patch and already configure apache and PHP. but on configuration (fourth step) must i running all configuration? or only the one of i needed? 
3.  maybe dou you have another link reference for detail step by step install it?  

please correct me if i'm wrong that step, because nothing details or best practices installation and configuring snipeIT. 
many thanks for your support and help..  😃

**Comment by elpijitigakilo** [comment]
(1/1) UnexpectedValueException
The stream or file "/var/www/html/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

in StreamHandler.php (line 107)
at StreamHandler->write(array('message' => 'exception \'UnexpectedValueException\' with message \'The stream or file "/var/www/html/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied\' in /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107Stack trace:#0 /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 /var/www/html/snipe-it/app/Exceptions/Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 /var/www/html/snipe-it/app/Exceptions/Handler.php(39): Illuminate\\Support\\Facades\\Log::error(Object(UnexpectedValueException))#8 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#9 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#10 /var/www/html/snipe-it/public/index.php(59): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#11 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'production', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2018-04-30 09:50:27] production.ERROR: exception \'UnexpectedValueException\' with message \'The stream or file "/var/www/html/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied\' in /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107Stack trace:#0 /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 /var/www/html/snipe-it/app/Exceptions/Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 /var/www/html/snipe-it/app/Exceptions/Handler.php(39): Illuminate\\Support\\Facades\\Log::error(Object(UnexpectedValueException))#8 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#9 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#10 /var/www/html/snipe-it/public/index.php(59): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#11 {main} '))
in AbstractProcessingHandler.php (line 37)
at AbstractProcessingHandler->handle(array('message' => 'exception \'UnexpectedValueException\' with message \'The stream or file "/var/www/html/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied\' in /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107Stack trace:#0 /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 /var/www/html/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 /var/www/html/snipe-it/app/Exceptions/Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 /var/www/html/snipe-it/app/Exceptions/Handler.php(39): Illuminate\\Support\\Facades\\Log::error(Object(UnexpectedValueException))#8 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#9 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#10 /var/www/html/snipe-it/public/index.php(59): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#11 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'production', 'datetime' => object(DateTime), 'extra' => array()))
in Logger.php (line 337)
at Logger->addRecord(400, object(UnexpectedValueException), array())
in Logger.php (line 616)
at Logger->error(object(UnexpectedValueException), array())
in Writer.php (line 203)
at Writer->writeLog('error', object(UnexpectedValueException), array())
in Writer.php (line 114)
at Writer->error(object(UnexpectedValueException))
in Facade.php (line 221)
at Facade::__callStatic('error', array(object(UnexpectedValueException)))
in Handler.php (line 39)
at Log::error(object(UnexpectedValueException))
in Handler.php (line 39)
at Handler->report(object(UnexpectedValueException))
in HandleExceptions.php (line 81)
at HandleExceptions->handleException(object(UnexpectedValueException))

**Comment by EarlRamirez** [comment]
@elpijitigakilo check the permission of the storage directory, you must have access to write to the log, use chmod -R 0775 /var/www/html/snipe-it/storage, the permission is the same for the public directory. If SELinux is enabled check the label of /var/www/html/snipe-it (httpd_sys_content_t) and /var/www/html/snipe-it (httpd_sys_rw_content_t). Then we can take it from there.

**Comment by elpijitigakilo** [comment]
![image](https://user-images.githubusercontent.com/38449160/39616816-79edb6d8-4fa7-11e8-8d46-552ef0e146eb.png)
still error,

**Comment by snipe** [comment]
@elpijitigakilo there is still a permission error, as evidenced by that error log. You can try 777, and/or check for SELinux, per the documentation. https://snipe-it.readme.io/docs/linuxosx#section-notes-on-selinux

The errors are telling you what's wrong - it cannot write to the directory.
