### ISSUE TITLE
Asset / users are missing. 

### ISSUE THREAD

**Issue by abdulsukur** [snipe/snipe-it#5381]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
expect all the information of users / assets are reflected on the system
-----

#### Actual Behavior

(what actually happens goes here)
All information is missing. assets are pointed to a users but when clicking user name, the users is not found or missing. 
items are not linked to the users. 

-----

#### Please confirm you have done the following before posting your bug report:

- [Yes ] I have enabled debug mode 
- [ Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh Install but database is reused from previous server backup. 
- Version of Snipe-IT you're running
4.2.0
- Version of PHP you're running
PHP 7.0.28-0ubuntu0.16.04.1 (cli)

- Version of MySQL/MariaDB you're running
MariaDB Server version:         10.1.32-MariaDB-1~xenial mariadb.org binary distribution

- What OS and web server you're running Snipe-IT on
Description:    Ubuntu 16.04.4 LTS

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Whoops, looks like something went wrong.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
all items/users/consumable pages are missing information
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
no
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
n/a

- Include any additional information you can find in `storage/logs` and your webserver's logs.
THis is some of it. Many more there. 
#15 /var/www/snipeit/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/snipeit/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/snipeit/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}

- Include what you've done so far in the installation, and if you got any error messages along the way.
restore previous backup / restore from storage/private_uploads
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I need a more complete stack trace to be able to assist you.
