### ISSUE TITLE
Importing Fails with Sample Data - Trying to get property of non-object

### ISSUE THREAD

**Issue by coolbaughm** [snipe/snipe-it#5818]
#### Expected Behavior (or desired behavior if a feature request)

I'm having problems with Importing data including importing data from the sample csvs.

-----

#### Actual Behavior

Using this single line as a testI'm getting an error

`Full Name,Email,Username,item Name,Category,Model name,Manufacturer,Model Number,Serial number,Asset Tag,Location,Notes,Purchase Date,Purchase Cost,Company,Status,Warranty,Supplier
Bonnie Nelson,bnelson0@cdbaby.com,bnelson0,eget nunc donec quis,quam,massa id,Linkbridge,6377018600094472,27aa8378-b0f4-4289-84a4-405da95c6147,970882174-8,Daping,"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",2016-04-05,133289.59,Alpha,Undeployable,14,Blogspan,`

  php artisan snipeit:import --verbose test.csv
======= Importing Items from test.csv =========
Custom Key: category
Category quam was created
Custom Key: company
Company Alpha was created
Custom Key: location
Location Daping was created
Custom Key: manufacturer
Manufacturer Linkbridge was created
Custom Key: status
Creating a new status
Status Undeployable was created
Custom Key: supplier
Supplier Blogspan was created
Custom Key: item name
Custom Key: notes
Custom Key: order number
Custom Key: purchase cost
Custom Key: purchase date
Custom Key: purchase date
Custom Key: quantity
Custom Key: requestable
Custom Key: serial
Custom Key: checkout type
Custom Key: full name
Custom Key: email
Custom Key: username
User Bonnie created
Custom Key: asset tag
No Matching Asset, Creating a new one
Custom Key: image
Custom Key: warranty
Custom Key: model name
Custom Key: model number
No Matching Model, Creating a new one
Asset Model massa id with model number 6377018600094472 was created
Asset eget nunc donec quis with serial number  was created

In Loggable.php line 44:

  [ErrorException]
  Trying to get property of non-object

Exception trace:
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /var/www/html/app/Models/Loggable.php:44
 App\Models\Asset->logCheckout() at /var/www/html/app/Models/Asset.php:197
 App\Models\Asset->checkOut() at /var/www/html/app/Importer/AssetImporter.php:117
 App\Importer\AssetImporter->createAssetIfNotExists() at /var/www/html/app/Importer/AssetImporter.php:41
 App\Importer\AssetImporter->handle() at /var/www/html/app/Importer/Importer.php:139
 App\Importer\Importer->App\Importer\{closure}() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:29
 Illuminate\Database\Connection->transaction() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:327
 Illuminate\Database\DatabaseManager->__call() at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
 Illuminate\Support\Facades\Facade::__callStatic() at /var/www/html/app/Importer/Importer.php:146
 App\Importer\Importer->import() at /var/www/html/app/Console/Commands/ObjectImportCommand.php:82
 App\Console\Commands\ObjectImportCommand->fire() at n/a:n/a
 call_user_func_array() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:539
 Illuminate\Container\Container->call() at /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
 Illuminate\Console\Command->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /var/www/html/vendor/symfony/console/Application.php:946
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/html/artisan:35

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh

- Version of Snipe-IT you're running
Latest

- Version of PHP you're running
7.0
- Version of MySQL/MariaDB you're running
5.7
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04 / Nginx
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Commandline php artisan snipeit:import --verbose test.csv
- If a stacktrace is provided in the error, include that too.
`[2018-07-11 14:36:44] production.ERROR: ErrorException: Trying to get property of non-object in /var/www/html/app/Models/Loggable.php:44
Stack trace:
#0 /var/www/html/app/Models/Loggable.php(44): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/html/a...', 44, Array)
#1 /var/www/html/app/Models/Asset.php(197): App\Models\Asset->logCheckout(NULL, Object(App\Models\User))
#2 /var/www/html/app/Importer/AssetImporter.php(117): App\Models\Asset->checkOut(Object(App\Models\User))
#3 /var/www/html/app/Importer/AssetImporter.php(41): App\Importer\AssetImporter->createAssetIfNotExists(Array)
#4 /var/www/html/app/Importer/Importer.php(139): App\Importer\AssetImporter->handle(Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): App\Importer\Importer->App\Importer\{closure}(Object(Illuminate\Database\MySqlConnection))
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(327): Illuminate\Database\Connection->transaction(Object(Closure))
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#8 /var/www/html/app/Importer/Importer.php(146): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#9 /var/www/html/app/Console/Commands/ObjectImportCommand.php(82): App\Importer\Importer->import()
#10 [internal function]: App\Console\Commands\ObjectImportCommand->fire()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#16 /var/www/html/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /var/www/html/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\ObjectImportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}
[2018-07-11 14:36:44] production.ERROR: ErrorException: Trying to get property of non-object in /var/www/html/app/Models/Loggable.php:44
Stack trace:
#0 /var/www/html/app/Models/Loggable.php(44): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/html/a...', 44, Array)
#1 /var/www/html/app/Models/Asset.php(197): App\Models\Asset->logCheckout(NULL, Object(App\Models\User))
#2 /var/www/html/app/Importer/AssetImporter.php(117): App\Models\Asset->checkOut(Object(App\Models\User))
#3 /var/www/html/app/Importer/AssetImporter.php(41): App\Importer\AssetImporter->createAssetIfNotExists(Array)
#4 /var/www/html/app/Importer/Importer.php(139): App\Importer\AssetImporter->handle(Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): App\Importer\Importer->App\Importer\{closure}(Object(Illuminate\Database\MySqlConnection))
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(327): Illuminate\Database\Connection->transaction(Object(Closure))
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#8 /var/www/html/app/Importer/Importer.php(146): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#9 /var/www/html/app/Console/Commands/ObjectImportCommand.php(82): App\Importer\Importer->import()
#10 [internal function]: App\Console\Commands\ObjectImportCommand->fire()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#16 /var/www/html/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /var/www/html/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\ObjectImportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}`

- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Probably not
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
No errors. I can add assets manually just fine.
- Indicate whether or not you've manually edited any data directly in the database
Nothing manually edited.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

Thanks for this application! It's amazing.

**Comment by coolbaughm** [comment]
I managed to find the underlying issue.

A import prior to the testing was done that had bad UTF-8 characters.  I just did a reset and I was able to complete the import from the Web GUI.
