### ISSUE TITLE
License checkout/in confirmation not working

### ISSUE THREAD

**Issue by Lewis14** [snipe/snipe-it#5906]
#### Please confirm you have done the following before posting your bug report:

- [Yes ] I have enabled debug mode 
- [Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
"Whoops, looks like something went wrong" message when checking in/out licenses. This includes existing licenses or any new ones I created to test this error.

The license does actually  checkout/in, but the system throws the error on the confirmation of this. After refreshing the dashboard page, the license change shows as working. 

**To Reproduce**
1. Go to licenses 
2. Click on Checkout
3. Select user
4. Press green checkout button
5. See error

(Error appears when checking in from the license page too)

**Expected behavior**
"License checked out successfully"

**Screenshots**
Step 1:
![chrome_2018-07-20_11-32-32](https://user-images.githubusercontent.com/41471929/42998853-93979290-8c13-11e8-81e3-e19a561b34db.jpg)
Step 2:
![chrome_2018-07-20_11-32-46](https://user-images.githubusercontent.com/41471929/42998870-a196a5a2-8c13-11e8-80a5-480f6a814e50.jpg)

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.2 - Build 3844
 - OS: Ubuntu Server 18.04 LTS
 - Web Server: Apache
 - PHP Version  7.2.7-0ubuntu0.18.04.2

**Desktop (please complete the following information):**
 - OS: Windows 10 1803 (tested IE11)
 - Browser: Chrome (tested IE11)
 - Version: 67.0.3396.99

_**Smartphone (please complete the following information):**
 - Version [e.g. 22]_

Error Messages

(1/1) ErrorExceptionTrying to get property of non-object
--
in License.php (line 231)
at HandleExceptions->handleError(8, 'Trying to get property of non-object', '/var/www/snipeit/app/Models/License.php', 231, array())in License.php (line 231)
at License->checkin_email()in CheckoutLicenseNotification.php (line 84)
at CheckoutLicenseNotification->via(object(User))in NotificationSender.php (line 84)
at NotificationSender->sendNow(object(Collection), object(CheckoutLicenseNotification))in NotificationSender.php (line 64)
at NotificationSender->send(object(Collection), object(CheckoutLicenseNotification))in ChannelManager.php (line 36)
at ChannelManager->send(object(User), object(CheckoutLicenseNotification))in RoutesNotifications.php (line 18)
at User->notify(object(CheckoutLicenseNotification))in Loggable.php (line 79)
at LicenseSeat->logCheckout('', object(User))in LicensesController.php (line 338)
at LicensesController->postCheckout(object(Request), '1')
at call_user_func_array(array(object(LicensesController), 'postCheckout'), array(object(Request), 'licenseId' => '1'))in Controller.php (line 55)
at Controller->callAction('postCheckout', array(object(Request), 'licenseId' => '1'))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(LicensesController), 'postCheckout')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 572)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 43)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php (line 49)
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php (line 49)
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php (line 42)
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 574)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 27)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

**- Include any additional information you can find in `storage/logs` and your webserver's logs:**

#0 /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(77): PDO->prepare('insert into `oa...', Array)
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(445): Doctrine\DBAL\Driver\PDOConnection->prepare('insert into `oa...')
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `oa...', Array)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('insert into `oa...', Array, Object(Closure))
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(450): Illuminate\Database\Connection->run('insert into `oa...', Array, Object(Closure))
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(404): Illuminate\Database\Connection->statement('insert into `oa...', Array)
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `oa...', Array)
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2133): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'in$
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1251): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(688): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(653): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(522): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 /var/www/snipeit/vendor/laravel/passport/src/ClientRepository.php(106): Illuminate\Database\Eloquent\Model->save()
#13 /var/www/snipeit/vendor/laravel/passport/src/ClientRepository.php(121): Laravel\Passport\ClientRepository->create(NULL, 'Snipe-IT Person...', 'http://localhos...', true)
#14 /var/www/snipeit/vendor/laravel/passport/src/Console/ClientCommand.php(61): Laravel\Passport\ClientRepository->createPersonalAccessClient(NULL, 'Snipe-IT Person...', 'http://localhos...')
#15 /var/www/snipeit/vendor/laravel/passport/src/Console/ClientCommand.php(37): Laravel\Passport\Console\ClientCommand->createPersonalClient(Object(Laravel\Passport\ClientRepository))
#16 [internal function]: Laravel\Passport\Console\ClientCommand->handle(Object(Laravel\Passport\ClientRepository))
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#22 /var/www/snipeit/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#23 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Con$
#24 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(197): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyl$
#25 /var/www/snipeit/vendor/laravel/passport/src/Console/InstallCommand.php(32): Illuminate\Console\Command->call('passport:client', Array)
#26 [internal function]: Laravel\Passport\Console\InstallCommand->handle()
#27 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#28 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#29 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#30 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#31 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#32 /var/www/snipeit/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#33 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Con$
#34 /var/www/snipeit/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#35 /var/www/snipeit/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Passport\Console\InstallCommand), Object(Symfony\Component\Console\Input\A$
#36 /var/www/snipeit/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\Buff$
#37 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(141): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Compon$
#38 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(220): Illuminate\Console\Application->call('passport:instal...', Object(Illuminate\Support\Collection), NULL)
#39 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Foundation\Console\Kernel->call('passport:instal...')
#40 /var/www/snipeit/app/Http/Controllers/SettingsController.php(260): Illuminate\Support\Facades\Facade::__callStatic('call', Array)
#41 [internal function]: App\Http\Controllers\SettingsController->getSetupMigrate()
#42 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#43 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('getSetupMigrate', Array)
#44 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\SettingsCo$
#45 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#46 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#47 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/snipeit/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/snipeit/app/Http/Middleware/CheckForTwoFactor.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

**Additional context**
- Is this a fresh install or an upgrade?  Built April 2018
- What OS and web server you're running Snipe-IT on - Ubuntu/Apache
- What method you used to install Snipe-IT -  Git auto method
- Include what you've done so far in the installation, and if you got any error messages along the way. - Nothing other than standard installation
- Indicate whether or not you've manually edited any data directly in the database - No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by FriedCircuits** [comment]
Hi, I had the same exact problem going from 4.4.2 to 4.6.2. So I reverted back to my VM snapshot.  I used the git method to upgrade.
