### ISSUE TITLE
LDAP Authentication Using MS Active Directory

### ISSUE THREAD

**Issue by coreyjackson** [snipe/snipe-it#6122]
- [ X ] I have enabled debug mode 
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I have read the LDAP configuration page at [https://snipe-it.readme.io/docs/ldap-sync-login](https://snipe-it.readme.io/docs/ldap-sync-login)  and was able to establish a connection to my LDAP server. I was also finally able to import my users by running this command : php artisan snipeit:ldap-sync --summary

The issue I have is that no user can login to snipe it with their active directory credentials.

**To Reproduce**
1. Go to snipe it login page
2. Enter the username as the samaccountname defined in AD
3. Enter the password as setup in AD
4. The following error appears on the screen: Error: The username or password is incorrect. The error that appears in the debugger window is as follows: production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory

**Expected behavior**
I expect the user to login to snipe it using their active directory credentials

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: Windows Server 2012 R2 (Build 9600)
 - Web Server: IIS 8
 - PHP Version: 7.2.7

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome and FireFox
 - Version: Chrome 68.0.3440.106 (64-bit), FireFox 61.0.2 (64-bit)

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
The error that appears in the snipe it debugger window is as follows: production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory

- Any errors that appear in your browser's error console.
No errors appear in the browser error console

This error is not reproducible on the demo: https://snipeitapp.com/demo.

- Include any additional information you can find in `storage/logs` and your webserver's logs.
error messages from storage/logs/laravel.log
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'ldap_search(): ...', 'C:\\inetpub\\wwwr...', 262, Array)
#1 C:\inetpub\wwwroot\snipe-it\app\Models\Ldap.php(262): ldap_search(Resource id #531, 'OU=Information ...', '((cn=*))')
#2 C:\inetpub\wwwroot\snipe-it\app\Console\Commands\LdapSync.php(77): App\Models\Ldap::findLdapUsers('OU=Information ...')
#3 [internal function]: App\Console\Commands\LdapSync->handle()
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(182): Illuminate\Container\Container->call(Array)
#9 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\LdapSync), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main}  
[2018-08-23 17:20:05] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory  
[2018-08-23 17:20:48] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory  
[2018-08-23 17:20:59] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory  
[2018-08-23 17:53:13] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory  
[2018-08-23 17:53:24] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory  
[2018-08-23 17:59:11] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory  

**Additional context**
- Is this a fresh install or an upgrade? Fresh Install
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manuall installation following instructions from snipe it
- Include what you've done so far in the installation, and if you got any error messages along the way: IIS Setup, PHP Setup, Composer Setup, Configured App Key, Completed Pre-Flight, Can login with admin account
![ldap_on](https://user-images.githubusercontent.com/28654341/44555929-70909a00-a705-11e8-8fac-ab0d36e51016.PNG)
![ldap_auth_failed](https://user-images.githubusercontent.com/28654341/44555935-72f2f400-a705-11e8-86a1-cf485d4cd1d0.PNG)
![ad_user_config](https://user-images.githubusercontent.com/28654341/44555939-771f1180-a705-11e8-94ed-cf9070ac33d2.PNG)

- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by Mynty100** [comment]
Try entering the bind user link this.

EG 1:
CN=IT ,OU=Service Accoutns,DC=tesc,DC=local
EG explained:
CN=username of LDAP accout,OU=Location of service account,DC=tesc,DC=local

Not sure on your setup and location of your LDAP service account but modify to suit your setup. I found using the email in the bind user does NOT always work.

Also, try with the LDAP filter the following.

&(objectClass=user)

Let us know how you go.
Thanking you,

**Comment by cjaxsn** [comment]
Thanks so much for the prompt response. I have tried both of your suggestions and same error occurs. I seen that the documentation showed providing the full OU Path for the LDAP Bind Username and tried this previously. Testing the LDAP connection is successful in using both the username@domain.com and full OU path and CN of the domain admin user. However, the issue still remains where users cannot authenticate and testing the LDAP login on the LDAP settings page results in: Login Failed. <username> did not successfully bind to LDAP.

Any other ideas? Is there any further debugging that can be performed to see exactly where the problem is?

Thank you in advance for your support.
