### ISSUE TITLE
Can Snipe-it be installed on a x86 QNAP NAS?

### ISSUE THREAD

**Issue by jovibroz** [snipe/snipe-it#6177]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by EarlRamirez** [comment]
@jovibroz what OS is your QNAP running?

**Comment by jovibroz** [comment]
I guess it's called QTS, QNAP Turbo Nas System.. :) 
But it's based on Linux though and you can install packages with Entware.
But I no skills in linux or programming but I understand the basics of using the terminal / ssh

**Comment by EarlRamirez** [comment]
The install.sh script may not work; however, the docs are really good so following it https://snipe-it.readme.io/docs/installation should not be a problem, let us know if you are stuck along the way and we will be happy to try and sort you out

**Comment by jovibroz** [comment]
Allright thanks, I'll give it a go when I have some hours to spend and get back to you. I managed to get rid of the DocumentRoot folder message, and got a blank page instead, probably because I didn't connect the.env to the mariadb... Well see how it goes :)

**Comment by jovibroz** [comment]
Lol I can't even find the .env file..? Is it part of snipe-it or Apache?

**Comment by jovibroz** [comment]
ls -a
....

**Comment by jovibroz** [comment]
Hmm... fatal unable to find remote helper for https..

**Comment by snipe** [comment]
That sounds like php isn't installed then? PHP would definitely be a requirement here.

**Comment by jovibroz** [comment]
[/usr/local/bin] # php-cli artisan key:generate
Could not open input file: artisan

And problems using composer.. :)

Fatal error: Uncaught Error: Call to undefined function Composer\Json\json_decode() in phar:///usr/local/bin/composer/src/Composer/Json/JsonFile.php:153
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Factory.php(290): Composer\Json\JsonFile->validateSchema(1)
#1 phar:///usr/local/bin/composer/src/Composer/Factory.php(440): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), '/root/.composer...', false, '/root/.composer', true)
#2 phar:///usr/local/bin/composer/src/Composer/Factory.php(420): Composer\Factory->createGlobalComposer(Object(Composer\IO\ConsoleIO), Object(Composer\Config), false, true)
#3 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(456): Composer\Factory::createGlobal(Object(Composer\IO\ConsoleIO), false)
#4 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(152): Composer\Console\Application->getPluginCommands()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Compo in phar:///usr/local/bin/composer/src/Composer/Json/JsonFile.php on line 153

**Comment by jovibroz** [comment]
So what happens inspite of all the error messages I dont understand is that the Do'h! message is gone and I see a blank page instead.
The only step I'm sure I didn't succeed in so far following the step by step guide. Is generating a key.
Maybe that's why the webpage is showing nothing?

Or should I just give up on this QNAP?

**Comment by snipe** [comment]
You have to run composer install first - that's how it downloads the libraries needed to generate your key, etc.

[Make sure php-json is installed](https://stackoverflow.com/questions/18239405/php-fatal-error-call-to-undefined-function-json-decode).

**Comment by jovibroz** [comment]
Downloading (100%)    Failed to download symfony/process from dist: The "https://codeload.github.com/symfony/process/legacy.zip/86cdb930a6a855b0ab35fb60c1504cb36184f843" file could not be written to /root/.composer/vendor/symfony/process/74b3bdc823314ef628feb8c83a41b445: Only 8192 of 44635 bytes written, possibly out of free disk space
    Now trying to download from source
  - Installing symfony/process (v4.1.4): Cloning 86cdb930a6
The disk hosting /root/.composer is full, this may be the cause of the following exception

                                                                                                                                                                                  
  [RuntimeException]                                                                                                                                                              
  Failed to clone https://github.com/symfony/process.git via https, ssh protocols, aborting.                                                                                      
                                                                                                                                                                                  
  - https://github.com/symfony/process.git                                                                                                                                        
    Cloning into '/root/.composer/vendor/symfony/process'...                                                                                                                      
    error: copy-fd: write returned: No space left on device                                                                                                                       
    fatal: cannot copy '/opt/share/git-core/templates/hooks/commit-msg.sample' to '/root/.composer/vendor/symfony/process/.git/hooks/commit-msg.sample': No space left on device  
                                                                                                                                                                                  
  - git@github.com:symfony/process.git                                                                                                                                            
    Cloning into '/root/.composer/vendor/symfony/process'...                                                                                                                      
    error: copy-fd: write returned: No space left on device                                                                                                                       
    fatal: cannot copy '/opt/share/git-core/templates/hooks/commit-msg.sample' to '/root/.composer/vendor/symfony/process/.git/hooks/commit-msg.sample': No space left on device

**Comment by jovibroz** [comment]
![skarmavbild 2018-09-13 kl 13 09 25](https://user-images.githubusercontent.com/43058168/45484978-42c3d180-b756-11e8-99f2-02650f87d256.png)

**Comment by jovibroz** [comment]
The NAS reports 700 GB free space.. Any clue? Or could it be write permission rather than space?

**Comment by jovibroz** [comment]
Aha that seals the deal and I give up :) The "DOM" is only 512 MB..

Thanks! 
This has been a journey! Hehe I've definitely learned a few things in this effort though :)

..I might get back if I find a better computer to run it on..

Thanks for your patience. 

Best,

Johan

**Comment by snipe** [comment]
Composer is the industry standard for installing and managing library dependencies in PHP.
