### ISSUE TITLE
500 error after new install

### ISSUE THREAD

**Issue by davidschmidt88** [snipe/snipe-it#6360]
Hi, I just installed latest version with the install script on a newly created Ubuntu VM 18.04.1 server.

I can't get anything on the web server, I get error 500.

Even with the recommended commands I get errors.
Any help is greatly appreciated!

```
snipeitapp@snapit:/var/www/snipeit$ php artisan config:clear
PHP Fatal error: Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:39
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(320): App\Exceptions\Handler->report(Object(Dotenv\Exception\InvalidFileException))
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(124): Illuminate\Foundation\Console\Kernel->reportException(Object(Dotenv\Exception\InvalidFileException))
#2 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 {main}
thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 39
```

**Comment by davidschmidt88** [comment]
Ok, solution is this: https://github.com/snipe/snipe-it/issues/5341

>
Ok found the error..
When the wizard finishes with the mail settings, I used a space in the MAIL_FROM_NAME & MAIL_REPLYTO_NAME. (Asset Management).
After removing this space in my .ENV file everything works. /var/www/snipeit/.env
