### ISSUE TITLE
Connection to mailserver timed out.

### ISSUE THREAD

**Issue by perezalvarezhi** [snipe/snipe-it#6408]
**#### Expected Behavior (or desired behavior if a feature request)**

I cant get the email smtp configuration to work, I expect to be able to send emails from my snipe it installation.

-----

#### Actual Behavior

When testing for smtp email
Error: An Error has occured! Connection to tcp://mail.txamericancitrus.com:465 Timed Out

-----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh
- Version of Snipe-IT you're running
 v4.6.4  build 3881 (g522dc1db2)
- Version of PHP you're running
PHP 7.0.32 (cli) (built: Nov  7 2018 04:55:01) ( NTS )
- Version of MySQL/MariaDB you're running
10.1.36-MariaDB-cll-lve - MariaDB Server 
- What OS and web server you're running Snipe-IT on
CloudLinux 7.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Softaculous Installer (I failed to do it manually since I dont have root)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Error: An Error has occured! Connection to tcp://mail.txamericancitrus.com:465 Timed Out
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
GeneralSettings > send test. (Test Email)
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.

```
[16:40:40] LOG.error: Swift_TransportException: Connection to tcp://mail.txamericancitrus.com:465 Timed Out in /home/txameric/public_html/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:404
Stack trace:
#0 /home/txameric/public_html/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(289): Swift_Transport_AbstractSmtpTransport->_getFullResponse(0)
#1 /home/txameric/public_html/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(117): Swift_Transport_AbstractSmtpTransport->_readGreeting()
#2 /home/txameric/public_html/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#3 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(443): Swift_Mailer->send(Object(Swift_Message), Array)
#4 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(217): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#5 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(60): Illuminate\Mail\Mailer->send(Object(Illuminate\Support\HtmlString), Array, Object(Closure))
#6 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\Notifications\Channels\MailChannel->send(Object(App\Models\Setting), Object(App\Notifications\MailTest))
#7 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\Models\Setting), '6b046a35-e28f-4...', Object(App\Notifications\MailTest), 'mail')
#8 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\MailTest))
#9 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(36): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\MailTest))
#10 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Notifications\ChannelManager->send(Object(App\Models\Setting), Object(App\Notifications\MailTest))
#11 /home/txameric/public_html/snipeit/app/Http/Controllers/Api/SettingsController.php(136): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#12 [internal function]: App\Http\Controllers\Api\SettingsController->ajaxTestEmail()
#13 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#14 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('ajaxTestEmail', Array)
#15 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\SettingsController), 'ajaxTestEmail')
#16 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#17 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#18 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#21 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#25 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#26 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#28 /home/txameric/public_html/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/txameric/public_html/snipeit/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/txameric/public_html/snipeit/app/Http/Middleware/CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/txameric/public_html/snipeit/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/txameric/public_html/snipeit/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/txameric/public_html/snipeit/app/Http/Middleware/ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/txameric/public_html/snipeit/app/Http/Middleware/ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /home/txameric/public_html/snipeit/app/Http/Middleware/XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /home/txameric/public_html/snipeit/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#65 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#66 /home/txameric/public_html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#67 /home/txameric/public_html/snipeit/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#68 {main}
```

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
Same as browser error log
- Include what you've done so far in the installation, and if you got any error messages along the way.

I checked other posts with similar problems and they told me to disable SELinux but I think it is already disabled. (https://github.com/snipe/snipe-it/issues/5743)
Changed the settings in .env file and used php artisan config:clear
My settings are:

```
# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=mail.txamericancitrus.com
MAIL_PORT=465
MAIL_USERNAME=soporte@txamericancitrus.com
MAIL_PASSWORD=**********
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=soporte@txamericancitrus.com
MAIL_FROM_NAME='Hugo Perez'
MAIL_REPLYTO_ADDR=soporte@txamericancitrus.com
MAIL_REPLYTO_NAME='HugoPerez'

```

- Indicate whether or not you've manually edited any data directly in the database
NO

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by jwhulette** [comment]
I checked your mail server using mxtoolbox.com. It erred out, so I think it's an issue with your mail server. 
[https://mxtoolbox.com/SuperTool.aspx?action=mx%3amail.txamericancitrus.com&run=toolpage#](https://mxtoolbox.com/SuperTool.aspx?action=mx%3amail.txamericancitrus.com&run=toolpage#)
Run the SMTP Test link

**Comment by perezalvarezhi** [comment]
Hi jwhulette thank you for your help, my hosting company told me that it was a MX discrepancy since I use barracuda for antispam but they said it is just the way it is and they cant do much.

I was not able to setit up with security but it worked on port 25.

I am not very happy with it but at least is working now.

**Comment by jwhulette** [comment]
@perezalvarezhi Can you close this issue since your issue is resolved.
