### ISSUE TITLE
PHP 7.3 compatibility

### ISSUE THREAD

**Issue by smb** [snipe/snipe-it#6491]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
PHP 7.3 changes the http://php.net/compact function:

> 7.3.0 | compact() now issues an E_NOTICE level error if a given string refers to an unset variable. Formerly, such strings have been silently skipped.

which breaks at least DepreciationsController.php (index), ManufacturersController.php (index) and ViewAssetsController.php (getRequestableIndex)

**To Reproduce**
1. Use PHP 7.3
2. Go to '/depreciations'
3. See error

**Server (please complete the following information):**
 - Snipe-IT Version: git develop 
 - OS: Ubuntu
 - Web Server: Nginx
 - PHP Version 7.3

**Error Messages**
```
[2018-12-06 22:50:18] production.ERROR: compact(): Undefined variable: user {"userId":1,"email":"sb@sbuehl.com","exception":"[object] (ErrorException(code: 0): compact(): Undefined variable: user at /webseiten/snipe.smb.wtf/app/Http/Controllers/ViewAssetsController.php:66)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'compact(): Unde...', '/webseiten/snip...', 66, Array)
#1 /webseiten/snipe.smb.wtf/app/Http/Controllers/ViewAssetsController.php(66): compact('user', 'assets', 'models')
#2 [internal function]: App\\Http\\Controllers\\ViewAssetsController->getRequestableIndex()
#3 /webseiten/snipe.smb.wtf/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#4 /webseiten/snipe.smb.wtf/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('getRequestableI...', Array)
#5 /webseiten/snipe.smb.wtf/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\ViewAssetsController), 'getRequestableI...')
#6 /webseiten/snipe.smb.wtf/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#7 /webseiten/snipe.smb.wtf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(679): Illuminate\\Routing\\Route->run()
#8 /webseiten/snipe.smb.wtf/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\
```

**Comment by snipe** [comment]
Ah, balls. Thanks for the heads up - we'll get those fixes out for you.

**Comment by snipe** [comment]
90 matches in 35 files. 😩

<img width="857" alt="screen shot 2018-12-12 at 6 07 19 pm" src="https://user-images.githubusercontent.com/197404/49910778-e21d6100-fe38-11e8-8fe2-0273161c6689.png">
