### ISSUE TITLE
Import through CLI gives Error

### ISSUE THREAD

**Issue by jackka** [snipe/snipe-it#6494]
SnipeIT (almost latest, develop branch): **3ed2f55 snipe on 06/12/18 at 06:56**  
PHP **7.2.10-0ubuntu0.18.04.1**
all cache clean and migrations was done
![image](https://user-images.githubusercontent.com/6271335/49698722-7c329e80-fbd8-11e8-9c22-f52f09261a93.png)

Sorry for too brevity report...

In addition.
err log from laravel debug bar:
[2018-12-09 17:25:53] production.ERROR: Call to undefined method Monolog\Logger::useFiles() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Monolog\\Logger::useFiles() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Log/Logger.php:273)
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(571): Illuminate\Log\Logger->__call('useFiles', Array)
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Illuminate\Log\LogManager->__call('useFiles', Array)
#2 /var/www/snipeit/app/Console/Commands/ObjectImportCommand.php(81): Illuminate\Support\Facades\Facade::__callStatic('useFiles', Array)
#3 [internal function]: App\Console\Commands\ObjectImportCommand->handle()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(571): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#9 /var/www/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 /var/www/snipeit/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/snipeit/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\ObjectImportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/snipeit/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 {main}

**Comment by jackka** [comment]
yes

**Comment by jackka** [comment]
I believe it was a glitch.
No need to keep it on hold
