### ISSUE TITLE
Cannot enter pre-flight: Call to undefined function Symfony\Polyfill\Mbstring\iconv_strpos()

### ISSUE THREAD

**Issue by whc2001** [snipe/snipe-it#6838]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Unable to start pre-flight procedure.
Checked for iconv and mbstring, all installed correctly.

```
# php --ri iconv

iconv

iconv support => enabled
iconv implementation => glibc
iconv library version => 2.28

Directive => Local Value => Master Value
iconv.input_encoding => no value => no value
iconv.output_encoding => no value => no value
iconv.internal_encoding => no value => no value


# php --ri mbstring

mbstring

Multibyte Support => enabled
Multibyte string engine => libmbfl
HTTP input encoding translation => disabled
libmbfl version => 1.3.2
oniguruma version => 6.9.0

mbstring extension makes use of "streamable kanji code filter and converter", which is distributed under the GNU Lesser General Public License version 2.1.

Multibyte (japanese) regex support => enabled
Multibyte regex (oniguruma) backtrack check => On
Multibyte regex (oniguruma) version => 6.9.0

Directive => Local Value => Master Value
mbstring.language => neutral => neutral
mbstring.detect_order => no value => no value
mbstring.http_input => no value => no value
mbstring.http_output => no value => no value
mbstring.internal_encoding => no value => no value
mbstring.substitute_character => no value => no value
mbstring.func_overload => 0 => 0
mbstring.encoding_translation => Off => Off
mbstring.http_output_conv_mimetypes => ^(text/|application/xhtml\+xml) => ^(text/|application/xhtml\+xml)
mbstring.strict_detection => Off => Off
```

**To Reproduce**
1. Finish "Download" "Configure" "Install Deps with Composer" "Generate AppKey"
2. Open pre-flight URL
3. Greeted by error message:
```

Fatal error: Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv_strpos() in /var/www/html/snipeit/vendor/symfony/polyfill-mbstring/Mbstring.php:500 Stack trace: #0 /var/www/html/snipeit/vendor/symfony/polyfill-mbstring/bootstrap.php(34): Symfony\Polyfill\Mbstring\Mbstring::mb_strpos(NULL, '/json', 0, 'UTF-8') #1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Support/Str.php(94): mb_strpos(NULL, '/json') #2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithContentTypes.php(34): Illuminate\Support\Str::contains(NULL, Array) #3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Http/Request.php(333): Illuminate\Http\Request->isJson() #4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Http/Request.php(361): Illuminate\Http\Request->getInputSource() #5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Http/Request.php(59): Illuminate\Http\Request::createFromBase(Object(Illuminate\Http\Request)) #6 /var/www/html/sn in /var/www/html/snipeit/vendor/symfony/polyfill-mbstring/Mbstring.php on line 500

```

**Server (please complete the following information):**
 - Snipe-IT Version : Should be latest, used `git clone` to pull two days ago.
 - OS: [e.g. Ubuntu, CentOS] : Debian 9
 - Web Server: [e.g. Apache, IIS] : Apache2
 - PHP Version : 7.3

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 22] : 72.0.3626.121

**Additional context**
- Is this a fresh install or an upgrade? : Fresh
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : Manual
- Indicate whether or not you've manually edited any data directly in the database : No

**Comment by snipe** [comment]
My guess would be that you don't have [mbstring](http://php.net/manual/en/mbstring.installation.php) installed or enabled. It's a [required](https://snipe-it.readme.io/docs/requirements) library. 

<img width="828" alt="Screen Shot 2019-03-19 at 4 11 58 PM" src="https://user-images.githubusercontent.com/197404/54647976-c93cd100-4a61-11e9-97e4-3f8cfd50f15e.png">

**Comment by snipe** [comment]
From a quick google search: You need to install http://php.net/manual/en/book.iconv.php PHP extension for this function support.

**Comment by whc2001** [comment]
```
# apt install php7.3-mbstring
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php7.3-mbstring is already the newest version (7.3.3-1).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.

# apt install php-mbstring
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  php-mbstring
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
Need to get 5,996 B of archives.
After this operation, 12.3 kB of additional disk space will be used.
Get:1 http://mirrors.linode.com/debian testing/main amd64 php-mbstring all 2:7.3+69 [5,996 B]
Fetched 5,996 B in 0s (198 kB/s)  
Selecting previously unselected package php-mbstring.
(Reading database ... 84058 files and directories currently installed.)
Preparing to unpack .../php-mbstring_2%3a7.3+69_all.deb ...
Unpacking php-mbstring (2:7.3+69) ...
Setting up php-mbstring (2:7.3+69) ...

# apt install php-iconv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package php-iconv is a virtual package provided by:
  php7.1-common 7.1.27-1+0~20190307202204.14+stretch~1.gbp7163d5
  php7.0-common 7.0.33-0+deb9u3
  php7.3-common 7.3.3-1
You should explicitly select one to install.

E: Package 'php-iconv' has no installation candidate

# apt install php7.3-iconv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php7.3-common' instead of 'php7.3-iconv'
php7.3-common is already the newest version (7.3.3-1).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.

# systemctl restart apache2
```
Problem still exists.

**Comment by snipe** [comment]
Snipe-IT v4.x is not compatible with PHP 7.3. You'll need to use a version of PHP between 5.6.4 and 7.2.x. This is due to a limitation of the underlying framework. The upcoming v5 will support 7.3+.

https://github.com/snipe/snipe-it/releases/tag/v4.6.14

**Comment by whc2001** [comment]
Thanks. Force downgraded to PHP7.2 with broken php7.2-curl then found I need to also downgrade MySQL and MariaDB or #4989 will happen.  Downgrading everything just for that is basically impractical so I'll wait for the new release.
