### ISSUE TITLE
Upgrading from v4.1.3->v4.6.15 causes empty asset listings with error date_interval_create_from_date_string(): Unknown or bad format ( months)

### ISSUE THREAD

**Issue by breisig** [snipe/snipe-it#6887]
**Describe the bug**
I have taken a backup and of my older SnipeIT (v4.1.3) and restored it on a fresh v4.6.15 system. Imported the DB and ran the upgrade.php script. When I log in to the system, I can see all the assets history in the main dashboard but when I click on the left hand side the 'Assets' and click on 'show all assets', nothing shows. It's all *empty*.

Looking at storage/logs/laravel.log, it seems when I click on the 'all assets', the following error appears.
```
[2019-04-05 09:39:19] production.ERROR: ErrorException: date_interval_create_from_date_string(): Unknown or bad format ( months) at position 0 (m): The timezone could not be found in the database in /html/snipeit-4.6.15/app/Presenters/AssetPresenter.php:396
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'date_interval_c...', '/html/snipeit-4...', 396, Array)
#1 /html/snipeit-4.6.15/app/Presenters/AssetPresenter.php(396): date_interval_create_from_date_string(' months')
#2 /html/snipeit-4.6.15/app/Http/Transformers/AssetsTransformer.php(34): App\Presenters\AssetPresenter->eol_date()
#3 /html/snipeit-4.6.15/app/Http/Transformers/AssetsTransformer.php(16): App\Http\Transformers\AssetsTransformer->transformAsset(Object(App\Models\Asset))
#4 /html/snipeit-4.6.15/app/Http/Controllers/Api/AssetsController.php(276): App\Http\Transformers\AssetsTransformer->transformAssets(Object(Illuminate\Database\Eloquent\Collection), 29)
#5 [internal function]: App\Http\Controllers\Api\AssetsController->index(Object(Illuminate\Http\Request))
#6 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#7 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('index', Array)
#8 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\AssetsController), 'index')
#9 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#10 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#11 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#14 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#18 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#19 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#21 /html/snipeit-4.6.15/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /html/snipeit-4.6.15/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /html/snipeit-4.6.15/app/Http/Middleware/CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /html/snipeit-4.6.15/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /html/snipeit-4.6.15/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /html/snipeit-4.6.15/app/Http/Middleware/ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /html/snipeit-4.6.15/app/Http/Middleware/ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /html/snipeit-4.6.15/app/Http/Middleware/XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /html/snipeit-4.6.15/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#62 /html/snipeit-4.6.15/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#63 /html/snipeit-4.6.15/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#64 {main}
```
Looking at my .env file, it also has...
```
APP_TIMEZONE='America/Winnipeg'
```

Looking at php.ini [php 7.2.17]
```
Default timezone => America/Winnipeg
date.timezone => America/Winnipeg => America/Winnipeg
```

What is this 'date_interval_create_from_date_string(): Unknown or bad format ( months) at position 0' all about and how to fix it?

**Comment by yorkhood** [comment]
I have the exact the same problem

**Comment by yorkhood** [comment]
The problem is that your leave asset EOL = 0, which causes the error.  Try to set the asset EOL more than 1

**Comment by breisig** [comment]
@yorkhood How would I do that to test?

**Comment by yorkhood** [comment]
> @yorkhood How would I do that to test?

I refer to the error message "date_interval_create_from_date_string(): Unknown or bad format ( months) at position 0", as it is "bad format ( months)", I guess something wrong here. And after I change the EOL to non-zero, the problem is gone.

**Comment by tnius** [comment]
I'm having the same error after upgrading.  Where would I go to change EOL?  Thanks!

**Comment by akam-it** [comment]
+1
Where to change EOL?

**Comment by ZephyriusOne** [comment]
The only place I see to change EOL is when you edit the asset model. It will show EOL field. I assume you will have to do this with all models one at a time.

@yorkhood Is there somewhere you can edit the default EOL instead of changing all models individually?

![image](https://user-images.githubusercontent.com/45017543/56136330-90a8ee00-5f60-11e9-9d88-96b5d5782b99.png)

**Comment by bbomgardner** [comment]
Also got this error this morning. I can confirm that setting all EOL to 0 solved the problem.

I used the [PATCH ](https://snipe-it.readme.io/reference#modelsid-2 ) API to update all of my models.

**Comment by akam-it** [comment]
/var/www/snipeit/app/Presenters/AssetPresenter.php

if I comment line 378 it is also work ok. without any EOL.

it is beta version, I reinstalled via install.sh to stable and all is ok.

**Comment by n0creativity** [comment]
We had the same issue and error in laravel.log after upgrading from 4.6.14 to 4.6.15 .
It seems, at least in our system, we had a large number of records with the value `NULL` in the `eol` field of the `snipeit.models` table.  I simply ran this SQL and it seemed to fix the issue...
```sql
UPDATE models SET eol = 0 WHERE eol IS NULL;
```

**Comment by bbomgardner** [comment]
Another symptom I noticed was this error occurs during historical custom report generation.

Is there another table where eol should be updated?

**Comment by jackka** [comment]
Faced with this problem today in the morning.  
I did not find any alarming symptoms, just crash in "All Assets" view. 
Thanks for advice with zeroing EOL.

**Comment by twisted3motions** [comment]
I get this whenever I try to generate a custom report.  

[2019-04-29 12:05:38] production.ERROR: ErrorException: date_interval_create_from_date_string(): Unknown or bad format ( months) at position 0 (m): The timezone could not be found in the database in /var/www/snipe-it/app/Presenters/AssetPresenter.php:496
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'date_interval_c...', '/var/www/snipe-...', 496, Array)
#1 /var/www/snipe-it/app/Presenters/AssetPresenter.php(496): date_interval_create_from_date_string(' months')
#2 /var/www/snipe-it/app/Http/Controllers/ReportsController.php(652): App\Presenters\AssetPresenter->warrantee_expires()
#3 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(39): App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}(Object(Illuminate\Database\Eloquent\Collection))
#4 /var/www/snipe-it/app/Http/Controllers/ReportsController.php(699): Illuminate\Database\Eloquent\Builder->chunk(500, Object(Closure))
#5 /var/www/snipe-it/vendor/symfony/http-foundation/StreamedResponse.php(114): App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}()

All of my EOL's are set to zero.  Used UPDATE models SET eol = 0 WHERE eol IS NULL;  No difference

**Comment by twisted3motions** [comment]
Setting them all to 1 made no difference either

**Comment by twisted3motions** [comment]
This seemed to fix it:  UPDATE assets SET warranty_months = 0 WHERE warranty_months IS NULL
