### ISSUE TITLE
Ldap sync error 

### ISSUE THREAD

**Issue by d90** [snipe/snipe-it#7153]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode - Yes I have
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - I was unable to find a solution to my issue

**Describe the bug**
After changing the LDAP filter in LDAP settings, I'm unable to import users through LDAP. Even after reverting to the original filter, which worked moments earlier,  the problem persists. I was able to replicate this in my test environment as well. 

**To Reproduce**
1. Go to 'Options(gear Icon)'
2. Click on 'LDAP'
3. Scroll down to 'LDAP FILTER'
4. Change the value
5. Go to 'people'>import
6. click sychronize

**Expected behavior**
users matching the new filter would be imported to the system

**Screenshots**
![snipe_ldapImportError](https://user-images.githubusercontent.com/10871791/59364382-c4a45380-8d04-11e9-8cc3-7387bf89743c.png)
-------------------------------------------------------
![snipe_ldapsettings](https://user-images.githubusercontent.com/10871791/59365295-52cd0980-8d06-11e9-9f28-40a3a0ea1ac3.png)

**Server:**
 - Snipe-IT Version v4.7.4 - build 4107 (master)
 - OS: [Docker\Alpipne]
 - Web Server: [nginx]
 - PHP Version 7.2.18

**Desktop:**
 - OS: [Windows 10]
 - Browser [Chrome,]
 - Version [Version 74.0.3729.169 (Official Build) (64-bit)]

**Error Messages**
- WITH DEBUG TURNED ON, 
[2019-06-05 10:22:55] production.ERROR: ldap_search(): Search: Invalid DN syntax {"userId":5,"email":"me@my.com","exception":"[object] (ErrorException(code: 0): ldap_search(): Search: Invalid DN syntax at /var/www/html/app/Models/Ldap.php:265)#69 /var/www/html/app/Http/Middleware/ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 /var/www/html/app/Http/Middleware/ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#73 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /var/www/html/app/Http/Middleware/XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#76 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#77 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 /var/www/html/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#80 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#82 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#83 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#85 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#86 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#88 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#89 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#90 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#91 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#92 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#93 /var/www/html/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#94 {main}  

**Additional context**
- Is this a fresh install or an upgrade? [Fresh Install]
- What OS and web server you're running Snipe-IT on [alpine\nginx]
- What method you used to install Snipe-IT [Docker]
- Include what you've done so far in the installation, and if you got any error messages along the way. [None]
- Indicate whether or not you've manually edited any data directly in the database. [I have not]

Cannot reproduce this on the demo. 

Testing LDAP sync and LDAP login is successful. I've tried removing spaces from the base bind DN. I've also tried changing the bind username format to user@domain, cn=username, dc=blahblah etc.

**Comment by d90** [comment]
It would appear that, on this version of snipe-it that I'm runnnig, every time you hit save on the LDAP settings page you must re-enter the bind user password. Failure to do this results in the above issue.
