### ISSUE TITLE
Unable to receive Email Notifications

### ISSUE THREAD

**Issue by sid8000** [snipe/snipe-it#7345]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
We have set daily schedule for expiring assets and licenses using Task scheduler because we are using Snipe-IT on Windows with WAMP.

We were receiving emails till 8th of August but for few days we were not receiving emails but there are still assets with expiring warranty.

**Expected behavior**
Notification should receive.

**Screenshots**
Email Error
![Email Error](https://user-images.githubusercontent.com/30995759/62847300-1bbda900-bcf3-11e9-9485-1a2f2d592785.png)
Batch File we are using with Task Scheduler
![batch file](https://user-images.githubusercontent.com/30995759/62847302-1e200300-bcf3-11e9-8c34-709189f92983.png)

**Server (please complete the following information):**
 - Snipe-IT Version - v4.7.5 build 4137
 - OS: [e.g. Ubuntu, CentOS] - Windows 7
 - Web Server: [e.g. Apache, IIS] - WAMP
 - PHP Version - 7.1.9

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 10
 - Browser [e.g. chrome, safari] - Google Chrome 
 - Version [e.g. 22] - 76

**Smartphone (please complete the following information):**

**Error Messages**
#30 {main}  
[2019-08-12 11:08:01] production.ERROR: Expected response code 354 but got code "503", with message "503 MAIL first (#5.5.1)
" {"exception":"[object] (Swift_TransportException(code: 503): Expected response code 354 but got code \"503\", with message \"503 MAIL first (#5.5.1)
\" at D:\\wamp\\www\\snipeit\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\AbstractSmtpTransport.php:457)
[stacktrace]
#0 D:\\wamp\\www\\snipeit\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('503 MAIL first ...', Array)
#1 D:\\wamp\\www\\snipeit\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('DATA\
\
', Array, Array, false, NULL)
#2 D:\\wamp\\www\\snipeit\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\AbstractSmtpTransport.php(390): Swift_Transport_EsmtpTransport->executeCommand('DATA\
\
', Array, Array)
#3 D:\\wamp\\www\\snipeit\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\AbstractSmtpTransport.php(497): Swift_Transport_AbstractSmtpTransport->doDataCommand(Array)
#4 D:\\wamp\\www\\snipeit\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\AbstractSmtpTransport.php(516): Swift_Transport_AbstractSmtpTransport->doMailTransaction(Object(Swift_Message), 'Sysadmin.Pune@c...', Array, Array)
#5 D:\\wamp\\www\\snipeit\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo(Object(Swift_Message), 'Sysadmin.Pune@c...', Array, Array)
#6 D:\\wamp\\www\\snipeit\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Mail\\Mailer.php(451): Swift_Mailer->send(Object(Swift_Message), Array)
#8 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Mail\\Mailer.php(235): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Message))
#9 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\Channels\\MailChannel.php(64): Illuminate\\Mail\\Mailer->send(Object(Illuminate\\Support\\HtmlString), Array, Object(Closure))
#10 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\NotificationSender.php(113): Illuminate\\Notifications\\Channels\\MailChannel->send(Object(App\\Models\\Recipients\\AlertRecipient), Object(App\\Notifications\\ExpiringAssetsNotification))
#11 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\NotificationSender.php(89): Illuminate\\Notifications\\NotificationSender->sendToNotifiable(Object(App\\Models\\Recipients\\AlertRecipient), 'a87ad1c0-3493-4...', Object(App\\Notifications\\ExpiringAssetsNotification), 'mail')
#12 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\NotificationSender.php(64): Illuminate\\Notifications\\NotificationSender->sendNow(Object(Illuminate\\Support\\Collection), Object(App\\Notifications\\ExpiringAssetsNotification))
#13 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Notifications\\ChannelManager.php(35): Illuminate\\Notifications\\NotificationSender->send(Object(Illuminate\\Support\\Collection), Object(App\\Notifications\\ExpiringAssetsNotification))
#14 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Notifications\\ChannelManager->send(Object(Illuminate\\Support\\Collection), Object(App\\Notifications\\ExpiringAssetsNotification))
#15 D:\\wamp\\www\\snipeit\\app\\Console\\Commands\\SendExpirationAlerts.php(65): Illuminate\\Support\\Facades\\Facade::__callStatic('send', Array)
#16 [internal function]: App\\Console\\Commands\\SendExpirationAlerts->handle()
#17 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(29): call_user_func_array(Array, Array)
#18 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#20 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#21 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(183): Illuminate\\Container\\Container->call(Array)
#22 D:\\wamp\\www\\snipeit\\vendor\\symfony\\console\\Command\\Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#23 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#24 D:\\wamp\\www\\snipeit\\vendor\\symfony\\console\\Application.php(960): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 D:\\wamp\\www\\snipeit\\vendor\\symfony\\console\\Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\SendExpirationAlerts), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 D:\\wamp\\www\\snipeit\\vendor\\symfony\\console\\Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 D:\\wamp\\www\\snipeit\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 D:\\wamp\\www\\snipeit\\artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 {main}
"} 

**Additional context**
- Is this a fresh install or an upgrade? 
Upgrade
- What OS and web server you're running Snipe-IT on
Windows 7 using WAMP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by sid8000** [comment]
Issue resolved.

Need to run following commands after updating Email settings in ENV file
php artisan config:clear
php artisan config:cache
