### ISSUE TITLE
System notification asset requested email not sending

### ISSUE THREAD

**Issue by MarkMcCloskey** [snipe/snipe-it#7368]
#### Expected Behavior (or desired behavior if a feature request)
The system notification documentation seems to imply that if a user requests an asset an email will be sent to an admin informing them of the request. Am I understanding this correctly?

Our use case may also include users directly requesting assets from other users. We would like the users themselves to be notified of the requests.

-----

#### Actual Behavior
Our admins receive no email informing them of the user request.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install
- Version of Snipe-IT you're running
Version 4.7.4 build 4107
- Version of PHP you're running
```
php --version
PHP 7.2.10 (cli) (built: Nov  7 2018 05:32:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

- Version of MySQL/MariaDB you're running
```
mysql --version
mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1
```

- What OS and web server you're running Snipe-IT on
Sanitized OS information:
```
hostnamectl
Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)
CPE OS Name: cpe:/o:redhat:enterprise_linux:7.6:GA:server
Kernel: Linux 3.10.0-957.el7.x86_64
Architecture: x86-64
```
Sanitized web server information:
```
httpd -v
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
```
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

Not sure these errors are related since the dates don't correlate to my issue.
```
[2019-08-15 14:19:54] production.ERROR: Command "snipeit" is not defined.

Did you mean one of these?
    snipeit:backup
    snipeit:counter-sync
    snipeit:create-admin
    snipeit:demo-settings
    snipeit:expected-checkin
    snipeit:expiring-alerts
    snipeit:import
    snipeit:import-locations
    snipeit:inventory-alerts
    snipeit:ldap-disable
    snipeit:ldap-sync
    snipeit:legacy-recrypt
    snipeit:pave
    snipeit:purge
    snipeit:regenerate-tags
    snipeit:restore-users
    snipeit:sync-asset-locations
    snipeit:travisci-install
    snipeit:unescape
    snipeit:upcoming-audits in /var/www/snipeit/vendor/symfony/console/Application.php:625

error
[2019-08-15 14:19:54] production.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException: Command "snipeit" is not defined.    snipeit:ldap-disable
    snipeit:ldap-sync
    snipeit:legacy-recrypt
    snipeit:pave
    snipeit:purge
    snipeit:regenerate-tags
    snipeit:restore-users
    snipeit:sync-asset-locations
    snipeit:travisci-install
    snipeit:unescape
    snipeit:upcoming-audits {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"snipeit\" is not defined.

Did you mean one of these?
    snipeit:backup
    snipeit:counter-sync
    snipeit:create-admin
    snipeit:demo-settings
    snipeit:expected-checkin
    snipeit:expiring-alerts
    snipeit:import
    snipeit:import-locations
    snipeit:inventory-alerts
    snipeit:ldap-disable
    snipeit:ldap-sync
    snipeit:legacy-recrypt
    snipeit:pave
    snipeit:purge
    snipeit:regenerate-tags
    snipeit:restore-users
    snipeit:sync-asset-locations
    snipeit:travisci-install
    snipeit:unescape
    snipeit:upcoming-audits at /var/www/snipeit/vendor/symfony/console/Application.php:625)
```

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Requestable asset page, request button.

- If a stacktrace is provided in the error, include that too.
```
[stacktrace]
#0 /var/www/snipeit/vendor/symfony/console/Application.php(236): Symfony\\Component\\Console\\Application->find('snipeit')
#1 /var/www/snipeit/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /var/www/snipeit/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 {main}
"}

Stack trace:
#0 /var/www/snipeit/vendor/symfony/console/Application.php(236): Symfony\Component\Console\Application->find('snipeit')
#1 /var/www/snipeit/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}  
```
- Any errors that appear in your browser's error console.
```
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ all.js?id=bf1b244d8cc9096e4a18:2
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:1
each @ all.js?id=bf1b244d8cc9096e4a18:1
each @ all.js?id=bf1b244d8cc9096e4a18:1
A @ all.js?id=bf1b244d8cc9096e4a18:1
on @ all.js?id=bf1b244d8cc9096e4a18:2
bind @ all.js?id=bf1b244d8cc9096e4a18:4
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:23
each @ all.js?id=bf1b244d8cc9096e4a18:1
each @ all.js?id=bf1b244d8cc9096e4a18:1
slimScroll @ all.js?id=bf1b244d8cc9096e4a18:23
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:26
u @ all.js?id=bf1b244d8cc9096e4a18:2
c @ all.js?id=bf1b244d8cc9096e4a18:2
all.js?id=bf1b244d8cc9096e4a18:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ all.js?id=bf1b244d8cc9096e4a18:2
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:1
each @ all.js?id=bf1b244d8cc9096e4a18:1
each @ all.js?id=bf1b244d8cc9096e4a18:1
A @ all.js?id=bf1b244d8cc9096e4a18:1
on @ all.js?id=bf1b244d8cc9096e4a18:2
bind @ all.js?id=bf1b244d8cc9096e4a18:4
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:23
each @ all.js?id=bf1b244d8cc9096e4a18:1
each @ all.js?id=bf1b244d8cc9096e4a18:1
slimScroll @ all.js?id=bf1b244d8cc9096e4a18:23
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:26
u @ all.js?id=bf1b244d8cc9096e4a18:2
c @ all.js?id=bf1b244d8cc9096e4a18:2
all.js?id=bf1b244d8cc9096e4a18:23 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:23
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:23
each @ all.js?id=bf1b244d8cc9096e4a18:1
each @ all.js?id=bf1b244d8cc9096e4a18:1
slimScroll @ all.js?id=bf1b244d8cc9096e4a18:23
(anonymous) @ all.js?id=bf1b244d8cc9096e4a18:26
u @ all.js?id=bf1b244d8cc9096e4a18:2
c @ all.js?id=bf1b244d8cc9096e4a18:2
all.js?id=bf1b244d8cc9096e4a18:2 [Violation] 'setTimeout' handler took 59ms
javascript?v=1551204114:4 [Violation] 'readystatechange' handler took 581ms
```
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.

Hard to say, I tried adding an admin email address to the demo system and requesting an item. I didn't receive an email.
 
- Include any additional information you can find in `storage/logs` and your webserver's logs.

laravel.log matches what is included above in stack traces and errors.
/var/log/httpd/error_log contains nothing related

- Include what you've done so far in the installation, and if you got any error messages along the way.

Here is a sanitized email portion of the .env

```
# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=localhost
MAIL_PORT=25
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=assettracker@our.address
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=assettracker@our.address
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_BACKUP_NOTIFICATION_ADDRESS=null

```
- Indicate whether or not you've manually edited any data directly in the database
No

Thank you!

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by SerjeiFaehrlich** [comment]
I have the same problem. Could you solve the issue by yourself?
