### ISSUE TITLE
apache error 500

### ISSUE THREAD

**Issue by CastyMcBoozer** [snipe/snipe-it#7419]
What the heck do I keep doing wrong?

I've followed so many different tutorials I don't even know where to begin.

First I installed using git clone, following all the instructions to install apache / mariadb / etc, and I never could get apache to answer.  I would get either the default apache page or 500 not found if I edited the sites-available/snipeit.conf page

After giving up on that method of installation, I installed via the install.sh script.  I left the defaults, so the hostname was ubuntu.  It worked!  Well for a minute...I didn't want it named ubuntu so I ran install.sh again and named it what I wanted, snipeit.foo.lan.  This time it answers, but now warns me that .env is readable by everyone.  What?  I didn't edit permissions on the .env file???

As soon as I make it so that .env isn't readable by the everyone group, apache fails to answer. Error 500.

Is it just impossible to change the name of the snipeit apache instance once it's installed?

**Comment by snipe** [comment]
First of all, take a deep breath :) That error is just a warning to make sure the .env isn’t accessible via a web url (since it contains sensitive info like your db credentials, app key, etc.) It shouldn’t be *world* readable, but Apache will need to read it in order to know what db to connect to, etc. as long as you can’t get to it via a web url, you should be fine. The process of checking file permissions isn’t as straightforward as it seems (especially across many OS’s), but that check is just to make sure folks don’t leave sensitive info out in the open.

**Comment by CastyMcBoozer** [comment]
I just wiped the VM, installed a fresh Ubuntu 18.04, ran the install.sh, set the server name to snipeit.lan.  All I get is HTTP 500 when trying to go to http://snipeit.lan

**Comment by CastyMcBoozer** [comment]
I have snipeit.lan in my hosts file and it resolves correctly when using ping and nslookup

**Comment by EarlRamirez** [comment]
> I just wiped the VM, installed a fresh Ubuntu 18.04, ran the install.sh, set the server name to snipeit.lan. All I get is HTTP 500 when trying to go to http://snipeit.lan

What error are you seeing in the apache error logs? Can you share the errors when debugging is enabled?

**Comment by CastyMcBoozer** [comment]
Looks like a bunch of php7 errors:

```
[Mon Sep 09 21:18:40.194296 2019] [php7:error] [pid 41470] [client 10.0.8.2:62867] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:40\nStack trace:\n#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 40
[Mon Sep 09 21:18:40.361670 2019] [php7:error] [pid 41467] [client 10.0.8.2:62868] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:40\nStack trace:\n#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 40
[Mon Sep 09 21:18:40.553750 2019] [php7:error] [pid 41466] [client 10.0.8.2:62869] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:40\nStack trace:\n#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 40
[Mon Sep 09 21:18:40.681202 2019] [php7:error] [pid 41510] [client 10.0.8.2:62870] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:40\nStack trace:\n#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 40
[Mon Sep 09 21:18:40.848359 2019] [php7:error] [pid 41469] [client 10.0.8.2:62871] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:40\nStack trace:\n#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 40
[Mon Sep 09 21:18:41.001634 2019] [php7:error] [pid 41468] [client 10.0.8.2:62872] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:40\nStack trace:\n#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 40
[Tue Sep 10 13:39:53.075553 2019] [php7:error] [pid 41470] [client 10.0.8.2:63380] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:40\nStack trace:\n#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 40

```

**Comment by CastyMcBoozer** [comment]
Found solution in another thread.  Can't have a space in MAIL_REPLYTO_NAME in the .env file.
