### ISSUE TITLE
Can't upload logo

### ISSUE THREAD

**Issue by cpthomp** [snipe/snipe-it#768]
Hello,

I'm trying to upload a png logo for the banner and whenever I hit save, I get this: Server Error: 500 (Internal Server Error). Is this a known bug or is there something I can do on my side?

In the error logs:
[2015-04-27 15:27:25] production.ERROR: exception 'Intervention\Image\Exception\NotSupportedException' with message 'GD Library extension not available with this PHP installation.' in /var/www/snipeit/vendor/intervention/image/src/Intervention/Image/Gd/Driver.php:18
Stack trace:
#0 /var/www/snipeit/vendor/intervention/image/src/Intervention/Image/ImageManager.php(107): Intervention\Image\Gd\Driver->__construct()
#1 /var/www/snipeit/vendor/intervention/image/src/Intervention/Image/ImageManager.php(50): Intervention\Image\ImageManager->createDriver()
#2 /var/www/snipeit/vendor/intervention/image/src/Intervention/Image/ImageManagerStatic.php(57): Intervention\Image\ImageManager->make('/tmp/phpeqNFTn')
#3 /var/www/snipeit/app/controllers/admin/SettingsController.php(96): Intervention\Image\ImageManagerStatic::make('/tmp/phpeqNFTn')
#4 [internal function]: Controllers\Admin\SettingsController->postEdit()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postEdit', Array)
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\SettingsController), Object(Illuminate\Routing\Route), 'postEdit')
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(962): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'postEdit')
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(777): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(747): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(643): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 /var/www/snipeit/public/index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []

Thanks!

**Comment by cpthomp** [comment]
Oh, and also, users can't upload avatars.

**Comment by cpthomp** [comment]
Nvm.. got it fixed. had to install php-gd: yum install php-gd --enablerepo=remi,remi-php55
