### ISSUE TITLE
Bulk edit not working

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#913]
Everything's fine running v2.0-pre except bulk editing:
```
[2015-07-14 14:27:13] production.ERROR: exception 'BadMethodCallException' with message 'Method [postBulkEdit] does not exist.' in D:\SYSTEM\WPN-XM\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:268
Stack trace:
#0 [internal function]: Illuminate\Routing\Controller->__call('postBulkEdit', Array)
#1 [internal function]: Controllers\Admin\UsersController->postBulkEdit()
#2 D:\SYSTEM\WPN-XM\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#3 D:\SYSTEM\WPN-XM\www\snipe-it\bootstrap\compiled.php(5847): Illuminate\Routing\Controller->callAction('postBulkEdit', Array)
#4 D:\SYSTEM\WPN-XM\www\snipe-it\bootstrap\compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\UsersController), Object(Illuminate\Routing\Route), 'postBulkEdit')
#5 D:\SYSTEM\WPN-XM\www\snipe-it\bootstrap\compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'postBulkEdit')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 D:\SYSTEM\WPN-XM\www\snipe-it\bootstrap\compiled.php(5398): call_user_func_array(Object(Closure), Array)
#8 D:\SYSTEM\WPN-XM\www\snipe-it\bootstrap\compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 D:\SYSTEM\WPN-XM\www\snipe-it\bootstrap\compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 D:\SYSTEM\WPN-XM\www\snipe-it\bootstrap\compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\SYSTEM\WPN-XM\www\snipe-it\bootstrap\compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\SYSTEM\WPN-XM\www\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 D:\SYSTEM\WPN-XM\www\snipe-it\bootstrap\compiled.php(7825): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 D:\SYSTEM\WPN-XM\www\snipe-it\bootstrap\compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 D:\SYSTEM\WPN-XM\www\snipe-it\bootstrap\compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 D:\SYSTEM\WPN-XM\www\snipe-it\bootstrap\compiled.php(11070): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 D:\SYSTEM\WPN-XM\www\snipe-it\bootstrap\compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 D:\SYSTEM\WPN-XM\www\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []
```
Do I need to run "composer update" in order to fix this?

Thanks.

**Comment by diekmanu** [comment]
This only happens when trying to bulk edit users.

**Comment by madd15** [comment]
Currently there are no controller methods for this section that I am aware of

**Comment by diekmanu** [comment]
Okay, looking forward to seeing this implemented. =)
